In [1]:
#import everything that you can
from langchain.prompts import PromptTemplate
from langchain.chains import SequentialChain
from langchain.chains import LLMChain
from dotenv import load_dotenv
import os
import sys
import openai
from langchain.chains import ConversationalRetrievalChain, RetrievalQA
from langchain.chat_models import ChatOpenAI
from langchain.document_loaders import DirectoryLoader, TextLoader
from langchain_openai import OpenAIEmbeddings
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.llms import OpenAI
from langchain.vectorstores import Chroma
import glob

In [4]:
load_dotenv()

True

In [5]:
os.environ["OPENAI_API_KEY"]  = os.getenv("OPENAI_API_KEY")

In [7]:
filepath = os.getcwd() + "\datasets"
csv_files = glob.glob(os.path.join(filepath, "*.csv"))
file1 = csv_files[1]
file1

'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv'

In [8]:
from langchain.document_loaders.csv_loader import CSVLoader

In [9]:
loader = CSVLoader(file1)
loader

In [10]:
data = loader.load()
data

[Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 0}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Cincinnati, OH\nPrices: $13,500\nLink: https://www.facebook.com//marketplace/item/849204949875598/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 1}, page_content='Model: Mazda mazda6 Touring\nYear: 2014\nMiles: 103K miles\nLocation: Cincinnati, OH\nPrices: $9,000\nLink: https://www.facebook.com//marketplace/item/1886928771721324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 2}, page_content='Model: Mazda mazda6 i Grand Touring Sedan 4D\nYear: 2012\nMiles: 198K miles\nLocation: Cincinnati, OH\nPrices: $2,300\nLink: https://www.facebook.com//marketplace/item/7697104893659305/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 3}, page_content='Model: Mazda mazda3 i Touring Sedan 4D\nYear: 2012\nMiles: 133K miles Â· Dealership\nLocation: Amelia, OH\nPrices: $5,499\nLink: https://www.facebook.com//marketplace/item/1193698368329198/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 4}, page_content='Model: Mazda rx-8\nYear: 2009\nMiles: 105K miles\nLocation: Covington, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/1425991878072270/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 5}, page_content='Model: Kia rio Sedan 4D\nYear: 2005\nMiles: 52K miles\nLocation: Franklin, OH\nPrices: $3,700\nLink: https://www.facebook.com//marketplace/item/1634392977405943/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 6}, page_content='Model: Volkswagen passat SE Sedan 4D\nYear: 2021\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $14,999\nLink: https://www.facebook.com//marketplace/item/452508747595343/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 7}, page_content='Model: Honda civic LX Sedan 4D\nYear: 2016\nMiles: 72K miles\nLocation: Loveland, OH\nPrices: $4,300\nLink: https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 8}, page_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2011\nMiles: 105K miles\nLocation: Cincinnati, OH\nPrices: $3,900\nLink: https://www.facebook.com//marketplace/item/389139410382677/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 9}, page_content='Model: Toyota camry SE Nightshade Edition Sedan 4D\nYear: 2020\nMiles: 42K miles\nLocation: Batavia, OH\nPrices: $24,799\nLink: https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 10}, page_content='Model: Volkswagen jetta 2.0L Sedan 4D\nYear: 2013\nMiles: 92K miles\nLocation: Cincinnati, OH\nPrices: $3,995\nLink: https://www.facebook.com//marketplace/item/1470971147139018/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 11}, page_content='Model: Honda civic EX-L Sedan 4D\nYear: 2016\nMiles: 112K miles\nLocation: Fairfield, OH\nPrices: $15,900\nLink: https://www.facebook.com//marketplace/item/312949561855953/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 12}, page_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/793179319550673/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 13}, page_content='Model: Toyota camry SE Sedan 4D\nYear: 2011\nMiles: 1.5K miles\nLocation: Cincinnati, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/913248610111916/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 14}, page_content='Model: Nissan versa SV Sedan 4D\nYear: 2016\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,999\nLink: https://www.facebook.com//marketplace/item/1468102077411591/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 15}, page_content='Model: Volkswagen passat 1.8T S Sedan 4D\nYear: 2014\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/2797800350385367/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 16}, page_content='Model: Toyota camry SE Sedan 4D\nYear: 2023\nMiles: 25K miles\nLocation: Cincinnati, OH\nPrices: $26,000\nLink: https://www.facebook.com//marketplace/item/318779907859818/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 17}, page_content='Model: Honda civic Sport Sedan 4D\nYear: 2020\nMiles: 86K miles\nLocation: Milford, OH\nPrices: $7,900\nLink: https://www.facebook.com//marketplace/item/456832023947846/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 18}, page_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2017\nMiles: 162K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1505703037010414/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 19}, page_content='Model: Volkswagen golf sportwagen TSI S Wagon 4D\nYear: 2015\nMiles: 124K miles\nLocation: Cincinnati, OH\nPrices: $1\nLink: https://www.facebook.com//marketplace/item/1509142776696300/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 20}, page_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2018\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/3771629319765742/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 21}, page_content='Model: Toyota corolla LE Sedan 4D\nYear: 2010\nMiles: 71K miles\nLocation: Fairfield, OH\nPrices: $7,899\nLink: https://www.facebook.com//marketplace/item/1695624710841197/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 22}, page_content='Model: Honda accord EX-L Sedan 4D\nYear: 2011\nMiles: 140K miles\nLocation: Cincinnati, OH\nPrices: $5,990\nLink: https://www.facebook.com//marketplace/item/1024652219659840/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 23}, page_content='Model: BMW 3 series 328i Coupe 2D\nYear: 2009\nMiles: 96K miles\nLocation: Cincinnati, OH\nPrices: $5,999\nLink: https://www.facebook.com//marketplace/item/1122003765563427/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 24}, page_content='Model: Volkswagen jetta sportwagen 2.0L TDI Sport Wagon 4D\nYear: 2014\nMiles: 118K miles\nLocation: Fort Mitchell, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/758004839600204/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 25}, page_content='Model: Hyundai sonata SE Sedan 4D\nYear: 2012\nMiles: 148K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/3860018704235595/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 26}, page_content='Model: Honda civic EX Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Loveland, OH\nPrices: $15,000\nLink: https://www.facebook.com//marketplace/item/886956419247442/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 27}, page_content='Model: Honda accord Sport Sedan 4D\nYear: 2018\nMiles: 80K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1394720905249548/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 28}, page_content='Model: Toyota corolla S Sedan 4D\nYear: 2002\nMiles: 182K miles\nLocation: Latonia, KY\nPrices: $2,800\nLink: https://www.facebook.com//marketplace/item/399813385862543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 29}, page_content='Model: Volkswagen jetta 2.5L SE Sedan 4D\nYear: 2012\nMiles: 179K miles\nLocation: Fairfield, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/478194458295191/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 30}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2009\nMiles: 230K miles\nLocation: Cincinnati, OH\nPrices: $3,420\nLink: https://www.facebook.com//marketplace/item/432756156398834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 31}, page_content='Model: Hyundai sonata Limited Sedan 4D\nYear: 2012\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/838322631559734/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 32}, page_content='Model: Honda civic EX Sedan 4D\nYear: 2009\nMiles: 180K miles\nLocation: Cincinnati, OH\nPrices: $4,800\nLink: https://www.facebook.com//marketplace/item/458475810397361/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 33}, page_content='Model: Toyota corolla S Sedan 4D\nYear: 2016\nMiles: 68K miles\nLocation: Monroe, OH\nPrices: $9,499\nLink: https://www.facebook.com//marketplace/item/839001347723641/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 34}, page_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2014\nMiles: 145K miles\nLocation: Cincinnati, OH\nPrices: $5,200\nLink: https://www.facebook.com//marketplace/item/1188259665661224/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 35}, page_content='Model: Mazda mazda3 i Touring Value Sedan 4D\nYear: 2009\nMiles: 155K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1121641699087714/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 36}, page_content='Model: Mazda\nYear: 2007\nMiles: 131K miles\nLocation: Goshen, OH\nPrices: $3,595\nLink: https://www.facebook.com//marketplace/item/843849801024330/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 37}, page_content='Model: Honda accord se\nYear: 2011\nMiles: 159K miles\nLocation: Covington, KY\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1025445862919955/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),

In [20]:
len(data)

679

In [64]:
max_rows = 120  # Adjust this number based on your needs and the data size
truncated_data = data[:max_rows]
truncated_data

[Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 0}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Cincinnati, OH\nPrices: $13,500\nLink: https://www.facebook.com//marketplace/item/849204949875598/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 1}, page_content='Model: Mazda mazda6 Touring\nYear: 2014\nMiles: 103K miles\nLocation: Cincinnati, OH\nPrices: $9,000\nLink: https://www.facebook.com//marketplace/item/1886928771721324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 2}, page_content='Model: Mazda mazda6 i Grand Touring Sedan 4D\nYear: 2012\nMiles: 198K miles\nLocation: Cincinnati, OH\nPrices: $2,300\nLink: https://www.facebook.com//marketplace/item/7697104893659305/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 3}, page_content='Model: Mazda mazda3 i Touring Sedan 4D\nYear: 2012\nMiles: 133K miles Â· Dealership\nLocation: Amelia, OH\nPrices: $5,499\nLink: https://www.facebook.com//marketplace/item/1193698368329198/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 4}, page_content='Model: Mazda rx-8\nYear: 2009\nMiles: 105K miles\nLocation: Covington, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/1425991878072270/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 5}, page_content='Model: Kia rio Sedan 4D\nYear: 2005\nMiles: 52K miles\nLocation: Franklin, OH\nPrices: $3,700\nLink: https://www.facebook.com//marketplace/item/1634392977405943/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 6}, page_content='Model: Volkswagen passat SE Sedan 4D\nYear: 2021\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $14,999\nLink: https://www.facebook.com//marketplace/item/452508747595343/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 7}, page_content='Model: Honda civic LX Sedan 4D\nYear: 2016\nMiles: 72K miles\nLocation: Loveland, OH\nPrices: $4,300\nLink: https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 8}, page_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2011\nMiles: 105K miles\nLocation: Cincinnati, OH\nPrices: $3,900\nLink: https://www.facebook.com//marketplace/item/389139410382677/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 9}, page_content='Model: Toyota camry SE Nightshade Edition Sedan 4D\nYear: 2020\nMiles: 42K miles\nLocation: Batavia, OH\nPrices: $24,799\nLink: https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 10}, page_content='Model: Volkswagen jetta 2.0L Sedan 4D\nYear: 2013\nMiles: 92K miles\nLocation: Cincinnati, OH\nPrices: $3,995\nLink: https://www.facebook.com//marketplace/item/1470971147139018/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 11}, page_content='Model: Honda civic EX-L Sedan 4D\nYear: 2016\nMiles: 112K miles\nLocation: Fairfield, OH\nPrices: $15,900\nLink: https://www.facebook.com//marketplace/item/312949561855953/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 12}, page_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/793179319550673/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 13}, page_content='Model: Toyota camry SE Sedan 4D\nYear: 2011\nMiles: 1.5K miles\nLocation: Cincinnati, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/913248610111916/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 14}, page_content='Model: Nissan versa SV Sedan 4D\nYear: 2016\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,999\nLink: https://www.facebook.com//marketplace/item/1468102077411591/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 15}, page_content='Model: Volkswagen passat 1.8T S Sedan 4D\nYear: 2014\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/2797800350385367/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 16}, page_content='Model: Toyota camry SE Sedan 4D\nYear: 2023\nMiles: 25K miles\nLocation: Cincinnati, OH\nPrices: $26,000\nLink: https://www.facebook.com//marketplace/item/318779907859818/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 17}, page_content='Model: Honda civic Sport Sedan 4D\nYear: 2020\nMiles: 86K miles\nLocation: Milford, OH\nPrices: $7,900\nLink: https://www.facebook.com//marketplace/item/456832023947846/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 18}, page_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2017\nMiles: 162K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1505703037010414/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 19}, page_content='Model: Volkswagen golf sportwagen TSI S Wagon 4D\nYear: 2015\nMiles: 124K miles\nLocation: Cincinnati, OH\nPrices: $1\nLink: https://www.facebook.com//marketplace/item/1509142776696300/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 20}, page_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2018\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/3771629319765742/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 21}, page_content='Model: Toyota corolla LE Sedan 4D\nYear: 2010\nMiles: 71K miles\nLocation: Fairfield, OH\nPrices: $7,899\nLink: https://www.facebook.com//marketplace/item/1695624710841197/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 22}, page_content='Model: Honda accord EX-L Sedan 4D\nYear: 2011\nMiles: 140K miles\nLocation: Cincinnati, OH\nPrices: $5,990\nLink: https://www.facebook.com//marketplace/item/1024652219659840/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 23}, page_content='Model: BMW 3 series 328i Coupe 2D\nYear: 2009\nMiles: 96K miles\nLocation: Cincinnati, OH\nPrices: $5,999\nLink: https://www.facebook.com//marketplace/item/1122003765563427/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 24}, page_content='Model: Volkswagen jetta sportwagen 2.0L TDI Sport Wagon 4D\nYear: 2014\nMiles: 118K miles\nLocation: Fort Mitchell, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/758004839600204/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 25}, page_content='Model: Hyundai sonata SE Sedan 4D\nYear: 2012\nMiles: 148K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/3860018704235595/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 26}, page_content='Model: Honda civic EX Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Loveland, OH\nPrices: $15,000\nLink: https://www.facebook.com//marketplace/item/886956419247442/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 27}, page_content='Model: Honda accord Sport Sedan 4D\nYear: 2018\nMiles: 80K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1394720905249548/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 28}, page_content='Model: Toyota corolla S Sedan 4D\nYear: 2002\nMiles: 182K miles\nLocation: Latonia, KY\nPrices: $2,800\nLink: https://www.facebook.com//marketplace/item/399813385862543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 29}, page_content='Model: Volkswagen jetta 2.5L SE Sedan 4D\nYear: 2012\nMiles: 179K miles\nLocation: Fairfield, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/478194458295191/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 30}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2009\nMiles: 230K miles\nLocation: Cincinnati, OH\nPrices: $3,420\nLink: https://www.facebook.com//marketplace/item/432756156398834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 31}, page_content='Model: Hyundai sonata Limited Sedan 4D\nYear: 2012\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/838322631559734/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 32}, page_content='Model: Honda civic EX Sedan 4D\nYear: 2009\nMiles: 180K miles\nLocation: Cincinnati, OH\nPrices: $4,800\nLink: https://www.facebook.com//marketplace/item/458475810397361/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 33}, page_content='Model: Toyota corolla S Sedan 4D\nYear: 2016\nMiles: 68K miles\nLocation: Monroe, OH\nPrices: $9,499\nLink: https://www.facebook.com//marketplace/item/839001347723641/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 34}, page_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2014\nMiles: 145K miles\nLocation: Cincinnati, OH\nPrices: $5,200\nLink: https://www.facebook.com//marketplace/item/1188259665661224/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 35}, page_content='Model: Mazda mazda3 i Touring Value Sedan 4D\nYear: 2009\nMiles: 155K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1121641699087714/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 36}, page_content='Model: Mazda\nYear: 2007\nMiles: 131K miles\nLocation: Goshen, OH\nPrices: $3,595\nLink: https://www.facebook.com//marketplace/item/843849801024330/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 37}, page_content='Model: Honda accord se\nYear: 2011\nMiles: 159K miles\nLocation: Covington, KY\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1025445862919955/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),

In [65]:
from langchain.chat_models import ChatOpenAI
from langchain.chains import ConversationalRetrievalChain
from langchain.schema import ChatMessage

In [66]:
llm = ChatOpenAI(model="gpt-3.5-turbo")
llm

ChatOpenAI(client=<openai.resources.chat.completions.Completions object at 0x000001DC2631DDD0>, async_client=<openai.resources.chat.completions.AsyncCompletions object at 0x000001DC2636FE10>, openai_api_key='sk-proj-arU1w4IbIlkHuXJbAHK9T3BlbkFJi1KvfrgbUWFVNgM2qHJq', openai_proxy='')

In [67]:
formatted_data = "\n".join([str(row) for row in truncated_data])
formatted_data

"page_content='Model: Toyota camry LE Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Cincinnati, OH\nPrices: $13,500\nLink: https://www.facebook.com//marketplace/item/849204949875598/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 0}\npage_content='Model: Mazda mazda6 Touring\nYear: 2014\nMiles: 103K miles\nLocation: Cincinnati, OH\nPrices: $9,000\nLink: https://www.facebook.com//marketplace/item/1886928771721324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 1}\npage_content='Model: Mazda mazda6 i Grand Touring Sedan 4D\nYear: 2012\nMiles: 198K miles\nLocation: Cincinnati, OH\nPrices: $2,300\nLink: https://www.facebook.com//marketplace/item/7697104893659305/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 2}\npage_content='Model: Mazda mazda3 i Touring Sedan 4D\nYear: 2012\nMiles: 133K miles Â· Dealership\nLocation: Amelia, OH\nPrices: $5,499\nLink: https://www.facebook.com//marketplace/item/1193698368329198/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 3}\npage_content='Model: Mazda rx-8\nYear: 2009\nMiles: 105K miles\nLocation: Covington, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/1425991878072270/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 4}\npage_content='Model: Kia rio Sedan 4D\nYear: 2005\nMiles: 52K miles\nLocation: Franklin, OH\nPrices: $3,700\nLink: https://www.facebook.com//marketplace/item/1634392977405943/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 5}\npage_content='Model: Volkswagen passat SE Sedan 4D\nYear: 2021\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $14,999\nLink: https://www.facebook.com//marketplace/item/452508747595343/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 6}\npage_content='Model: Honda civic LX Sedan 4D\nYear: 2016\nMiles: 72K miles\nLocation: Loveland, OH\nPrices: $4,300\nLink: https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 7}\npage_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2011\nMiles: 105K miles\nLocation: Cincinnati, OH\nPrices: $3,900\nLink: https://www.facebook.com//marketplace/item/389139410382677/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 8}\npage_content='Model: Toyota camry SE Nightshade Edition Sedan 4D\nYear: 2020\nMiles: 42K miles\nLocation: Batavia, OH\nPrices: $24,799\nLink: https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 9}\npage_content='Model: Volkswagen jetta 2.0L Sedan 4D\nYear: 2013\nMiles: 92K miles\nLocation: Cincinnati, OH\nPrices: $3,995\nLink: https://www.facebook.com//marketplace/item/1470971147139018/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 10}\npage_content='Model: Honda civic EX-L Sedan 4D\nYear: 2016\nMiles: 112K miles\nLocation: Fairfield, OH\nPrices: $15,900\nLink: https://www.facebook.com//marketplace/item/312949561855953/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 11}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/793179319550673/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 12}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2011\nMiles: 1.5K miles\nLocation: Cincinnati, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/913248610111916/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 13}\npage_content='Model: Nissan versa SV Sedan 4D\nYear: 2016\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,999\nLink: https://www.facebook.com//marketplace/item/1468102077411591/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 14}\npage_content='Model: Volkswagen passat 1.8T S Sedan 4D\nYear: 2014\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/2797800350385367/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 15}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2023\nMiles: 25K miles\nLocation: Cincinnati, OH\nPrices: $26,000\nLink: https://www.facebook.com//marketplace/item/318779907859818/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 16}\npage_content='Model: Honda civic Sport Sedan 4D\nYear: 2020\nMiles: 86K miles\nLocation: Milford, OH\nPrices: $7,900\nLink: https://www.facebook.com//marketplace/item/456832023947846/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 17}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2017\nMiles: 162K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1505703037010414/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 18}\npage_content='Model: Volkswagen golf sportwagen TSI S Wagon 4D\nYear: 2015\nMiles: 124K miles\nLocation: Cincinnati, OH\nPrices: $1\nLink: https://www.facebook.com//marketplace/item/1509142776696300/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 19}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2018\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/3771629319765742/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 20}\npage_content='Model: Toyota corolla LE Sedan 4D\nYear: 2010\nMiles: 71K miles\nLocation: Fairfield, OH\nPrices: $7,899\nLink: https://www.facebook.com//marketplace/item/1695624710841197/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 21}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2011\nMiles: 140K miles\nLocation: Cincinnati, OH\nPrices: $5,990\nLink: https://www.facebook.com//marketplace/item/1024652219659840/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 22}\npage_content='Model: BMW 3 series 328i Coupe 2D\nYear: 2009\nMiles: 96K miles\nLocation: Cincinnati, OH\nPrices: $5,999\nLink: https://www.facebook.com//marketplace/item/1122003765563427/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 23}\npage_content='Model: Volkswagen jetta sportwagen 2.0L TDI Sport Wagon 4D\nYear: 2014\nMiles: 118K miles\nLocation: Fort Mitchell, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/758004839600204/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 24}\npage_content='Model: Hyundai sonata SE Sedan 4D\nYear: 2012\nMiles: 148K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/3860018704235595/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 25}\npage_content='Model: Honda civic EX Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Loveland, OH\nPrices: $15,000\nLink: https://www.facebook.com//marketplace/item/886956419247442/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 26}\npage_content='Model: Honda accord Sport Sedan 4D\nYear: 2018\nMiles: 80K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1394720905249548/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 27}\npage_content='Model: Toyota corolla S Sedan 4D\nYear: 2002\nMiles: 182K miles\nLocation: Latonia, KY\nPrices: $2,800\nLink: https://www.facebook.com//marketplace/item/399813385862543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 28}\npage_content='Model: Volkswagen jetta 2.5L SE Sedan 4D\nYear: 2012\nMiles: 179K miles\nLocation: Fairfield, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/478194458295191/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 29}\npage_content='Model: Toyota camry LE Sedan 4D\nYear: 2009\nMiles: 230K miles\nLocation: Cincinnati, OH\nPrices: $3,420\nLink: https://www.facebook.com//marketplace/item/432756156398834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 30}\npage_content='Model: Hyundai sonata Limited Sedan 4D\nYear: 2012\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/838322631559734/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 31}\npage_content='Model: Honda civic EX Sedan 4D\nYear: 2009\nMiles: 180K miles\nLocation: Cincinnati, OH\nPrices: $4,800\nLink: https://www.facebook.com//marketplace/item/458475810397361/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 32}\npage_content='Model: Toyota corolla S Sedan 4D\nYear: 2016\nMiles: 68K miles\nLocation: Monroe, OH\nPrices: $9,499\nLink: https://www.facebook.com//marketplace/item/839001347723641/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 33}\npage_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2014\nMiles: 145K miles\nLocation: Cincinnati, OH\nPrices: $5,200\nLink: https://www.facebook.com//marketplace/item/1188259665661224/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 34}\npage_content='Model: Mazda mazda3 i Touring Value Sedan 4D\nYear: 2009\nMiles: 155K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1121641699087714/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 35}\npage_content='Model: Mazda\nYear: 2007\nMiles: 131K miles\nLocation: Goshen, OH\nPrices: $3,595\nLink: https://www.facebook.com//marketplace/item/843849801024330/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 36}\npage_content='Model: Honda accord se\nYear: 2011\nMiles: 159K miles\nLocation: Covington, KY\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1025445862919955/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 37}\npage_content='Model: Hyundai elantra SE Sedan 4D\nYear: 2015\nMiles: 144K miles\nLocation: Erlanger, KY\nPri

In [68]:
import re

In [69]:
pattern = re.compile(r"metadata=\{'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': (\d+)\}")
pattern

re.compile(r"metadata=\{'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': (\d+)\}",
           re.UNICODE)

In [70]:
def remove_file_path(match):
    return f"metadata={{'row': {match.group(1)}}}"

In [71]:
# Replace file path in the raw data
cleaned_data = pattern.sub(remove_file_path, formatted_data)
cleaned_data

"page_content='Model: Toyota camry LE Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Cincinnati, OH\nPrices: $13,500\nLink: https://www.facebook.com//marketplace/item/849204949875598/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 0}\npage_content='Model: Mazda mazda6 Touring\nYear: 2014\nMiles: 103K miles\nLocation: Cincinnati, OH\nPrices: $9,000\nLink: https://www.facebook.com//marketplace/item/1886928771721324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 1}\npage_content='Model: Mazda mazda6 i Grand Touring Sedan 4D\nYear: 2012\nMiles: 198K miles\nLocation: Cincinnati, OH\nPrices: $2,300\nLink: https://www.facebook.com//marketplace/item/7697104893659305/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 2}\npage_content='Model: Mazda mazda3 i Touring Sedan 4D\nYear: 2012\nMiles: 133K miles Â· Dealership\nLocation: Amelia, OH\nPrices: $5,499\nLink: https://www.facebook.com//marketplace/item/1193698368329198/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 3}\npage_content='Model: Mazda rx-8\nYear: 2009\nMiles: 105K miles\nLocation: Covington, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/1425991878072270/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 4}\npage_content='Model: Kia rio Sedan 4D\nYear: 2005\nMiles: 52K miles\nLocation: Franklin, OH\nPrices: $3,700\nLink: https://www.facebook.com//marketplace/item/1634392977405943/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 5}\npage_content='Model: Volkswagen passat SE Sedan 4D\nYear: 2021\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $14,999\nLink: https://www.facebook.com//marketplace/item/452508747595343/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 6}\npage_content='Model: Honda civic LX Sedan 4D\nYear: 2016\nMiles: 72K miles\nLocation: Loveland, OH\nPrices: $4,300\nLink: https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 7}\npage_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2011\nMiles: 105K miles\nLocation: Cincinnati, OH\nPrices: $3,900\nLink: https://www.facebook.com//marketplace/item/389139410382677/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 8}\npage_content='Model: Toyota camry SE Nightshade Edition Sedan 4D\nYear: 2020\nMiles: 42K miles\nLocation: Batavia, OH\nPrices: $24,799\nLink: https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 9}\npage_content='Model: Volkswagen jetta 2.0L Sedan 4D\nYear: 2013\nMiles: 92K miles\nLocation: Cincinnati, OH\nPrices: $3,995\nLink: https://www.facebook.com//marketplace/item/1470971147139018/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 10}\npage_content='Model: Honda civic EX-L Sedan 4D\nYear: 2016\nMiles: 112K miles\nLocation: Fairfield, OH\nPrices: $15,900\nLink: https://www.facebook.com//marketplace/item/312949561855953/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 11}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/793179319550673/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 12}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2011\nMiles: 1.5K miles\nLocation: Cincinnati, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/913248610111916/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 13}\npage_content='Model: Nissan versa SV Sedan 4D\nYear: 2016\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,999\nLink: https://www.facebook.com//marketplace/item/1468102077411591/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 14}\npage_content='Model: Volkswagen passat 1.8T S Sedan 4D\nYear: 2014\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/2797800350385367/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 15}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2023\nMiles: 25K miles\nLocation: Cincinnati, OH\nPrices: $26,000\nLink: https://www.facebook.com//marketplace/item/318779907859818/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 16}\npage_content='Model: Honda civic Sport Sedan 4D\nYear: 2020\nMiles: 86K miles\nLocation: Milford, OH\nPrices: $7,900\nLink: https://www.facebook.com//marketplace/item/456832023947846/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 17}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2017\nMiles: 162K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1505703037010414/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 18}\npage_content='Model: Volkswagen golf sportwagen TSI S Wagon 4D\nYear: 2015\nMiles: 124K miles\nLocation: Cincinnati, OH\nPrices: $1\nLink: https://www.facebook.com//marketplace/item/1509142776696300/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 19}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2018\nMiles: 88K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/3771629319765742/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 20}\npage_content='Model: Toyota corolla LE Sedan 4D\nYear: 2010\nMiles: 71K miles\nLocation: Fairfield, OH\nPrices: $7,899\nLink: https://www.facebook.com//marketplace/item/1695624710841197/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 21}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2011\nMiles: 140K miles\nLocation: Cincinnati, OH\nPrices: $5,990\nLink: https://www.facebook.com//marketplace/item/1024652219659840/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 22}\npage_content='Model: BMW 3 series 328i Coupe 2D\nYear: 2009\nMiles: 96K miles\nLocation: Cincinnati, OH\nPrices: $5,999\nLink: https://www.facebook.com//marketplace/item/1122003765563427/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 23}\npage_content='Model: Volkswagen jetta sportwagen 2.0L TDI Sport Wagon 4D\nYear: 2014\nMiles: 118K miles\nLocation: Fort Mitchell, KY\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/758004839600204/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 24}\npage_content='Model: Hyundai sonata SE Sedan 4D\nYear: 2012\nMiles: 148K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/3860018704235595/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 25}\npage_content='Model: Honda civic EX Sedan 4D\nYear: 2017\nMiles: 79K miles\nLocation: Loveland, OH\nPrices: $15,000\nLink: https://www.facebook.com//marketplace/item/886956419247442/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 26}\npage_content='Model: Honda accord Sport Sedan 4D\nYear: 2018\nMiles: 80K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1394720905249548/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 27}\npage_content='Model: Toyota corolla S Sedan 4D\nYear: 2002\nMiles: 182K miles\nLocation: Latonia, KY\nPrices: $2,800\nLink: https://www.facebook.com//marketplace/item/399813385862543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 28}\npage_content='Model: Volkswagen jetta 2.5L SE Sedan 4D\nYear: 2012\nMiles: 179K miles\nLocation: Fairfield, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/478194458295191/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 29}\npage_content='Model: Toyota camry LE Sedan 4D\nYear: 2009\nMiles: 230K miles\nLocation: Cincinnati, OH\nPrices: $3,420\nLink: https://www.facebook.com//marketplace/item/432756156398834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 30}\npage_content='Model: Hyundai sonata Limited Sedan 4D\nYear: 2012\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/838322631559734/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 31}\npage_content='Model: Honda civic EX Sedan 4D\nYear: 2009\nMiles: 180K miles\nLocation: Cincinnati, OH\nPrices: $4,800\nLink: https://www.facebook.com//marketplace/item/458475810397361/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 32}\npage_content='Model: Toyota corolla S Sedan 4D\nYear: 2016\nMiles: 68K miles\nLocation: Monroe, OH\nPrices: $9,499\nLink: https://www.facebook.com//marketplace/item/839001347723641/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 33}\npage_content='Model: Hyundai sonata GLS Sedan 4D\nYear: 2014\nMiles: 145K miles\nLocation: Cincinnati, OH\nPrices: $5,200\nLink: https://www.facebook.com//marketplace/item/1188259665661224/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 34}\npage_content='Model: Mazda mazda3 i Touring Value Sedan 4D\nYear: 2009\nMiles: 155K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1121641699087714/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 35}\npage_content='Model: Mazda\nYear: 2007\nMiles: 131K miles\nLocation: Goshen, OH\nPrices: $3,595\nLink: https://www.facebook.com//marketplace/item/843849801024330/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 36}\npage_content='Model: Honda accord se\nYear: 2011\nMiles: 159K miles\nLocation: Covington, KY\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1025445862919955/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 37}\npage_content='Model: Hyundai elantra SE Sedan 4D\nYear: 2015\nMiles: 144K miles\nLocation: Erlanger, KY\nPrices: $6,000\nLink: https://www.facebook.com//marketplace/item/994314462277360/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 38}\npage_content='Model: Toyota corolla LE Sedan 4D\nYear: 2017\nMiles: 77K miles\nLocation: Cincinnati, OH\nPrices: $9,900\nLink: https://www.facebook.com//marketplace/item/474354345322029/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 39}\npage_content='Model: Hyundai elantra SE Sedan 4D\nYear: 2015\nMiles: 136K miles\nLocation: Amelia, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/860093849313449/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 40}\npage_content='Model: Honda accord LX Sedan 4D\nYear: 2016\nMiles: 118K miles\nLocation: Fairfield, OH\nPrices: $10,500\nLink: https://www.facebook.com//marketplace/item/832684661783220/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 41}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2015\nMiles: 125K miles\nLocation: West Chester, OH\nPrices: $5,800\nLink: https://www.facebook.com//marketplace/item/358208397296550/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 42}\npage_content='Model: Honda accord\nYear: 2012\nMiles: 148K miles\nLocation: Cincinnati, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/1122604742169092/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 43}\npage_content='Model: Toyota corolla\nYear: 2010\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $6,400\nLink: https://www.facebook.com//marketplace/item/854494276536445/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 44}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2006\nMiles: 71K miles\nLocation: Monroe, OH\nPrices: $6,399\nLink: https://www.facebook.com//marketplace/item/455906420732721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 45}\npage_content='Model: Jetta volkswagen sport\nYear: 2011\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/322391417601721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 46}\npage_content='Model: Volkswagen passat GLS Sedan 4D\nYear: 2003\nMiles: 159K miles\nLocation: Middletown, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/835541458523506/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 47}\npage_content='Model: Toyota corolla L Sedan 4D\nYear: 2017\nMiles: 140K miles\nLocation: Cincinnati, OH\nPrices: $11,000\nLink: https://www.facebook.com//marketplace/item/7309949619132085/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 48}\npage_content='Model: Nissan leaf S-24 Hatchback 4D\nYear: 2016\nMiles: 26K miles\nLocation: Fort Thomas, KY\nPrices: $6,000\nLink: https://www.facebook.com//marketplace/item/3792474441038159/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 49}\npage_content='Model: Toyota camry\nYear: 2007\nMiles: 180K miles\nLocation: West Chester, OH\nPrices: $3,750\nLink: https://www.facebook.com//marketplace/item/1510827582850275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 50}\npage_content='Model: Hyundai sonata Limited Sedan 4D\nYear: 2011\nMiles: 171K miles\nLocation: Milford, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/358295863747080/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 51}\npage_content='Model: Chevrolet cruze LT Sedan 4D\nYear: 2017\nMiles: 99K miles\nLocation: Cincinnati, OH\nPrices: $6,300\nLink: https://www.facebook.com//marketplace/item/515080010876043/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 52}\npage_content='Model: Hyundai santa fe sport Sport Utility 4D\nYear: 2013\nMiles: 77K miles\nLocation: Cincinnati, OH\nPrices: $12,400\nLink: https://www.facebook.com//marketplace/item/1375680396435006/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 53}\npage_content='Model: Kia rio S Sedan 4D\nYear: 2018\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $7,500\nLink: https://www.facebook.com//marketplace/item/849104227129740/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 54}\npage_content='Model: Hyundai sonata SE Sedan 4D\

In [72]:
len(cleaned_data)

42675

In [73]:
custom_prompt = f"""
Here is the data from the CSV file:\n{cleaned_data}\n\nPlease analyze this data and provide insights based on the following criteria:
1) Find the most  suitable car for me, I prefer toyota honda and mazda.
2) I prefer less miles and less money and the newer models.
3) also I dont want any dealership.
4) Share the link as well in the response
"""

In [74]:
llm = ChatOpenAI(model="gpt-3.5-turbo")
llm

ChatOpenAI(client=<openai.resources.chat.completions.Completions object at 0x000001DC26356190>, async_client=<openai.resources.chat.completions.AsyncCompletions object at 0x000001DC262E1950>, openai_api_key='sk-proj-arU1w4IbIlkHuXJbAHK9T3BlbkFJi1KvfrgbUWFVNgM2qHJq', openai_proxy='')

In [75]:
message = ChatMessage(role="user", content=custom_prompt)
response = llm([message])
answer1 = response.content
print(response.content,end='\n')

Based on your preferences, the most suitable car for you would be the 2017 Honda Civic LX Sedan 4D with 72K miles, priced at $4,300. It is located in Loveland, OH and the link to the listing is https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD

This car meets your criteria of being a Honda, having less mileage, being affordable, and not being sold by a dealership. It is also a relatively newer model from 2017.

In [76]:
max_rows = 120  # Adjust this number based on your needs and the data size
truncated_data = data[max_rows: 2 *max_rows]
truncated_data

[Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 120}, page_content='Model: Lexus nx 200t Sport Utility 4D\nYear: 2017\nMiles: 147K miles\nLocation: Cincinnati, OH\nPrices: $17,000\nLink: https://www.facebook.com//marketplace/item/776107654594806/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 121}, page_content='Model: Ford focus SE Sedan 4D\nYear: 2013\nMiles: 72K miles\nLocation: Fairfield, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1298916234846623/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 122}, page_content='Model: Porsche cayenne S Sport Utility 4D\nYear: 2004\nMiles: 191K miles\nLocation: Loveland, OH\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/496410932875254/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 123}, page_content='Model: Volkswagen jetta 2.0L Base Sedan 4D\nYear: 2014\nMiles: 137K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/420549837094259/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 124}, page_content='Model: Subaru legacy 2.5i Premium Sedan 4D\nYear: 2016\nMiles: 109K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/2654700638041405/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 125}, page_content='Model: Audi a4 1.8T Quattro Sedan 4D\nYear: 2004\nMiles: 126K miles\nLocation: Hamilton, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1638071446952897/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 126}, page_content='Model: Toyota corolla S Special Edition Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/1777726666084648/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 127}, page_content='Model: Toyota yaris Sedan 4D\nYear: 2008\nMiles: 207K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1700483824058284/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 128}, page_content='Model: Land Rover range rover HSE Sport Utility 4D\nYear: 2005\nMiles: 107K miles Â· Dealership\nLocation: Hamilton, OH\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1533212650955326/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 129}, page_content='Model: Toyota camry SE Sedan 4D\nYear: 2008\nMiles: 209K miles\nLocation: Franklin, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1677107559529517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 130}, page_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 112K miles\nLocation: Mason, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/3259807954163150/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 131}, page_content='Model: Ford focus se\nYear: 2014\nMiles: 202K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/352380731063081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 132}, page_content='Model: Toyota rav4\nYear: 2000\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/471666759138771/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 133}, page_content='Model: Chevrolet impala LTZ Sedan 4D\nYear: 2014\nMiles: 123K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/400141629708545/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 134}, page_content='Model: Buick le sabre Custom\nYear: 2001\nMiles: 13K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/3781756528729362/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 135}, page_content='Model: Acura ILX\nYear: 2019\nMiles: 43K miles\nLocation: Cincinnati, OH\nPrices: $14,500\nLink: https://www.facebook.com//marketplace/item/1005138321050008/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 136}, page_content='Model: Nissan altima 2.5 Sedan 4D\nYear: 2010\nMiles: 165K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/801142051804133/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 137}, page_content='Model: Toyota corolla\nYear: 2013\nMiles: 400 miles\nLocation: Cincinnati, OH\nPrices: $8,990\nLink: https://www.facebook.com//marketplace/item/438386274719003/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 138}, page_content='Model: Nissan versa\nYear: 2009\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1037957944613175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 139}, page_content='Model: Hyundai sonata Sedan 4D\nYear: 2003\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $2,399\nLink: https://www.facebook.com//marketplace/item/1720260141839755/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 140}, page_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 111K miles\nLocation: Fairfield, OH\nPrices: $9,850\nLink: https://www.facebook.com//marketplace/item/8207611969291247/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 141}, page_content='Model: Nissan versa SL Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1132833847775834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 142}, page_content='Model: Genesis g90 5.0 Ultimate Sedan 4D\nYear: 2021\nMiles: 22K miles\nLocation: Cincinnati, OH\nPrices: $51,118\nLink: https://www.facebook.com//marketplace/item/670265935284890/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 143}, page_content='Model: Toyota prius One Hatchback 4D\nYear: 2015\nMiles: 111K miles\nLocation: Cincinnati, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/1371683937563859/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 144}, page_content='Model: Lexus IS 350 Sport Sedan 4D\nYear: 2008\nMiles: 237K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/726398496192253/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 145}, page_content='Model: Chevrolet camaro LT Coupe 2D\nYear: 2012\nMiles: 108K miles\nLocation: Cincinnati, OH\nPrices: $7,200\nLink: https://www.facebook.com//marketplace/item/427355033049294/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 146}, page_content='Model: Toyota matrix S Sport Wagon 4D\nYear: 2009\nMiles: 148K miles\nLocation: Burlington, KY\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/791749699752081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 147}, page_content='Model: Mitsubishi lancer GTS Sedan 4D\nYear: 2010\nMiles: 162K miles\nLocation: Fort Mitchell, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/2215689042128543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 148}, page_content='Model: Chevrolet cruze LTZ Sedan 4D\nYear: 2015\nMiles: 113K miles\nLocation: Hebron, KY\nPrices: $123,456\nLink: https://www.facebook.com//marketplace/item/1401954563795275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 149}, page_content='Model: Honda crosstour EX-L Sport Utility 4D\nYear: 2012\nMiles: 153K miles\nLocation: Hamilton, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/987605822872560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 150}, page_content='Model: Chevrolet impala LT Sedan 4D\nYear: 2014\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/734720935354670/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 151}, page_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2007\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/833731498698015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 152}, page_content='Model: Mazda mazda6 s Sedan 4D\nYear: 2003\nMiles: 204K miles\nLocation: Cincinnati, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/3684694805134214/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 153}, page_content='Model: Hyundai tiburon GS Coupe 2D\nYear: 2006\nMiles: 123K miles\nLocation: Fairfield, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/1013458523831682/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 154}, page_content='Model: Infiniti q50 3.7 Sedan 4D\nYear: 2015\nMiles: 44K miles\nLocation: Erlanger, KY\nPrices: $18,500\nLink: https://www.facebook.com//marketplace/item/1122796235489721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 155}, page_content='Model: Tesla Model 3\nYear: 2018\nMiles: 33K miles\nLocation: Hamilton, OH\nPrices: $26,999\nLink: https://www.facebook.com//marketplace/item/967578921781014/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 156}, page_content='Model: Toyota 4runner SR5 Sport Utility 4D\nYear: 2011\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $16,995\nLink: https://www.facebook.com//marketplace/item/1699766200789007/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 157}, page_content='Model: Cadillac cts Sport Wagon 4D\nYear: 2012\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/296036426928990/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),

In [77]:
formatted_data = "\n".join([str(row) for row in truncated_data])
formatted_data

"page_content='Model: Lexus nx 200t Sport Utility 4D\nYear: 2017\nMiles: 147K miles\nLocation: Cincinnati, OH\nPrices: $17,000\nLink: https://www.facebook.com//marketplace/item/776107654594806/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 120}\npage_content='Model: Ford focus SE Sedan 4D\nYear: 2013\nMiles: 72K miles\nLocation: Fairfield, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1298916234846623/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 121}\npage_content='Model: Porsche cayenne S Sport Utility 4D\nYear: 2004\nMiles: 191K miles\nLocation: Loveland, OH\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/496410932875254/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 122}\npage_content='Model: Volkswagen jetta 2.0L Base Sedan 4D\nYear: 2014\nMiles: 137K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/420549837094259/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 123}\npage_content='Model: Subaru legacy 2.5i Premium Sedan 4D\nYear: 2016\nMiles: 109K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/2654700638041405/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 124}\npage_content='Model: Audi a4 1.8T Quattro Sedan 4D\nYear: 2004\nMiles: 126K miles\nLocation: Hamilton, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1638071446952897/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 125}\npage_content='Model: Toyota corolla S Special Edition Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/1777726666084648/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 126}\npage_content='Model: Toyota yaris Sedan 4D\nYear: 2008\nMiles: 207K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1700483824058284/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 127}\npage_content='Model: Land Rover range rover HSE Sport Utility 4D\nYear: 2005\nMiles: 107K miles Â· Dealership\nLocation: Hamilton, OH\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1533212650955326/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 128}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2008\nMiles: 209K miles\nLocation: Franklin, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1677107559529517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 129}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 112K miles\nLocation: Mason, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/3259807954163150/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 130}\npage_content='Model: Ford focus se\nYear: 2014\nMiles: 202K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/352380731063081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 131}\npage_content='Model: Toyota rav4\nYear: 2000\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/471666759138771/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 132}\npage_content='Model: Chevrolet impala LTZ Sedan 4D\nYear: 2014\nMiles: 123K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/400141629708545/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 133}\npage_content='Model: Buick le sabre Custom\nYear: 2001\nMiles: 13K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/3781756528729362/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 134}\npage_content='Model: Acura ILX\nYear: 2019\nMiles: 43K miles\nLocation: Cincinnati, OH\nPrices: $14,500\nLink: https://www.facebook.com//marketplace/item/1005138321050008/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 135}\npage_content='Model: Nissan altima 2.5 Sedan 4D\nYear: 2010\nMiles: 165K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/801142051804133/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 136}\npage_content='Model: Toyota corolla\nYear: 2013\nMiles: 400 miles\nLocation: Cincinnati, OH\nPrices: $8,990\nLink: https://www.facebook.com//marketplace/item/438386274719003/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 137}\npage_content='Model: Nissan versa\nYear: 2009\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1037957944613175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 138}\npage_content='Model: Hyundai sonata Sedan 4D\nYear: 2003\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $2,399\nLink: https://www.facebook.com//marketplace/item/1720260141839755/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 139}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 111K miles\nLocation: Fairfield, OH\nPrices: $9,850\nLink: https://www.facebook.com//marketplace/item/8207611969291247/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 140}\npage_content='Model: Nissan versa SL Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1132833847775834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 141}\npage_content='Model: Genesis g90 5.0 Ultimate Sedan 4D\nYear: 2021\nMiles: 22K miles\nLocation: Cincinnati, OH\nPrices: $51,118\nLink: https://www.facebook.com//marketplace/item/670265935284890/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 142}\npage_content='Model: Toyota prius One Hatchback 4D\nYear: 2015\nMiles: 111K miles\nLocation: Cincinnati, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/1371683937563859/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 143}\npage_content='Model: Lexus IS 350 Sport Sedan 4D\nYear: 2008\nMiles: 237K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/726398496192253/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 144}\npage_content='Model: Chevrolet camaro LT Coupe 2D\nYear: 2012\nMiles: 108K miles\nLocation: Cincinnati, OH\nPrices: $7,200\nLink: https://www.facebook.com//marketplace/item/427355033049294/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 145}\npage_content='Model: Toyota matrix S Sport Wagon 4D\nYear: 2009\nMiles: 148K miles\nLocation: Burlington, KY\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/791749699752081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 146}\npage_content='Model: Mitsubishi lancer GTS Sedan 4D\nYear: 2010\nMiles: 162K miles\nLocation: Fort Mitchell, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/2215689042128543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 147}\npage_content='Model: Chevrolet cruze LTZ Sedan 4D\nYear: 2015\nMiles: 113K miles\nLocation: Hebron, KY\nPrices: $123,456\nLink: https://www.facebook.com//marketplace/item/1401954563795275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 148}\npage_content='Model: Honda crosstour EX-L Sport Utility 4D\nYear: 2012\nMiles: 153K miles\nLocation: Hamilton, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/987605822872560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 149}\npage_content='Model: Chevrolet impala LT Sedan 4D\nYear: 2014\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/734720935354670/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 150}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2007\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/833731498698015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 151}\npage_content='Model: Mazda mazda6 s Sedan 4D\nYear: 2003\nMiles: 204K miles\nLocation: Cincinnati, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/3684694805134214/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 152}\npage_content='Model: Hyundai tiburon GS Coupe 2D\nYear: 2006\nMiles: 123K miles\nLocation: Fairfield, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/1013458523831682/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 153}\npage_content='Model: Infiniti q50 3.7 Sedan 4D\nYear: 2015\nMiles: 44K miles\nLocation: Erlanger, KY\nPrices: $18,500\nLink: https://www.facebook.com//marketplace/item/1122796235489721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 154}\npage_content='Model: Tesla Model 3\nYear: 2018\nMiles: 33K miles\nLocation: Hamilton, OH\nPrices: $26,999\nLink: https://www.facebook.com//marketplace/item/967578921781014/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 155}\npage_content='Model: Toyota 4runner SR5 Sport Utility 4D\nYear: 2011\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $16,995\nLink: https://www.facebook.com//marketplace/item/1699766200789007/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 156}\npage_content='Model: Cadillac cts Sport Wagon 4D\nYear: 2012\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/296036426928990/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'source': 'C:\\\\Users\\\\gauur\\\\projects\\\\Fifth Third\\\\finale_fidelity\\\\Car_Price_Facebook_Marketpalce\\\\datasets\\\\2024-07-10-Cincinnati-Ohio.csv', 'row': 157}\npage_content='Model: Ford mustang GT Premium Convertible 2D\nYea

In [78]:
import re

In [79]:
# Replace file path in the raw data
cleaned_data = pattern.sub(remove_file_path, formatted_data)
cleaned_data

"page_content='Model: Lexus nx 200t Sport Utility 4D\nYear: 2017\nMiles: 147K miles\nLocation: Cincinnati, OH\nPrices: $17,000\nLink: https://www.facebook.com//marketplace/item/776107654594806/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 120}\npage_content='Model: Ford focus SE Sedan 4D\nYear: 2013\nMiles: 72K miles\nLocation: Fairfield, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1298916234846623/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 121}\npage_content='Model: Porsche cayenne S Sport Utility 4D\nYear: 2004\nMiles: 191K miles\nLocation: Loveland, OH\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/496410932875254/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 122}\npage_content='Model: Volkswagen jetta 2.0L Base Sedan 4D\nYear: 2014\nMiles: 137K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/420549837094259/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 123}\npage_content='Model: Subaru legacy 2.5i Premium Sedan 4D\nYear: 2016\nMiles: 109K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/2654700638041405/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 124}\npage_content='Model: Audi a4 1.8T Quattro Sedan 4D\nYear: 2004\nMiles: 126K miles\nLocation: Hamilton, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1638071446952897/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 125}\npage_content='Model: Toyota corolla S Special Edition Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/1777726666084648/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 126}\npage_content='Model: Toyota yaris Sedan 4D\nYear: 2008\nMiles: 207K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1700483824058284/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 127}\npage_content='Model: Land Rover range rover HSE Sport Utility 4D\nYear: 2005\nMiles: 107K miles Â· Dealership\nLocation: Hamilton, OH\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1533212650955326/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 128}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2008\nMiles: 209K miles\nLocation: Franklin, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1677107559529517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 129}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 112K miles\nLocation: Mason, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/3259807954163150/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 130}\npage_content='Model: Ford focus se\nYear: 2014\nMiles: 202K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/352380731063081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 131}\npage_content='Model: Toyota rav4\nYear: 2000\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/471666759138771/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 132}\npage_content='Model: Chevrolet impala LTZ Sedan 4D\nYear: 2014\nMiles: 123K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/400141629708545/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 133}\npage_content='Model: Buick le sabre Custom\nYear: 2001\nMiles: 13K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/3781756528729362/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 134}\npage_content='Model: Acura ILX\nYear: 2019\nMiles: 43K miles\nLocation: Cincinnati, OH\nPrices: $14,500\nLink: https://www.facebook.com//marketplace/item/1005138321050008/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 135}\npage_content='Model: Nissan altima 2.5 Sedan 4D\nYear: 2010\nMiles: 165K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/801142051804133/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 136}\npage_content='Model: Toyota corolla\nYear: 2013\nMiles: 400 miles\nLocation: Cincinnati, OH\nPrices: $8,990\nLink: https://www.facebook.com//marketplace/item/438386274719003/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 137}\npage_content='Model: Nissan versa\nYear: 2009\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1037957944613175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 138}\npage_content='Model: Hyundai sonata Sedan 4D\nYear: 2003\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $2,399\nLink: https://www.facebook.com//marketplace/item/1720260141839755/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 139}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 111K miles\nLocation: Fairfield, OH\nPrices: $9,850\nLink: https://www.facebook.com//marketplace/item/8207611969291247/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 140}\npage_content='Model: Nissan versa SL Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1132833847775834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 141}\npage_content='Model: Genesis g90 5.0 Ultimate Sedan 4D\nYear: 2021\nMiles: 22K miles\nLocation: Cincinnati, OH\nPrices: $51,118\nLink: https://www.facebook.com//marketplace/item/670265935284890/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 142}\npage_content='Model: Toyota prius One Hatchback 4D\nYear: 2015\nMiles: 111K miles\nLocation: Cincinnati, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/1371683937563859/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 143}\npage_content='Model: Lexus IS 350 Sport Sedan 4D\nYear: 2008\nMiles: 237K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/726398496192253/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 144}\npage_content='Model: Chevrolet camaro LT Coupe 2D\nYear: 2012\nMiles: 108K miles\nLocation: Cincinnati, OH\nPrices: $7,200\nLink: https://www.facebook.com//marketplace/item/427355033049294/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 145}\npage_content='Model: Toyota matrix S Sport Wagon 4D\nYear: 2009\nMiles: 148K miles\nLocation: Burlington, KY\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/791749699752081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 146}\npage_content='Model: Mitsubishi lancer GTS Sedan 4D\nYear: 2010\nMiles: 162K miles\nLocation: Fort Mitchell, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/2215689042128543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 147}\npage_content='Model: Chevrolet cruze LTZ Sedan 4D\nYear: 2015\nMiles: 113K miles\nLocation: Hebron, KY\nPrices: $123,456\nLink: https://www.facebook.com//marketplace/item/1401954563795275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 148}\npage_content='Model: Honda crosstour EX-L Sport Utility 4D\nYear: 2012\nMiles: 153K miles\nLocation: Hamilton, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/987605822872560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 149}\npage_content='Model: Chevrolet impala LT Sedan 4D\nYear: 2014\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/734720935354670/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 150}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2007\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/833731498698015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 151}\npage_content='Model: Mazda mazda6 s Sedan 4D\nYear: 2003\nMiles: 204K miles\nLocation: Cincinnati, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/3684694805134214/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 152}\npage_content='Model: Hyundai tiburon GS Coupe 2D\nYear: 2006\nMiles: 123K miles\nLocation: Fairfield, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/1013458523831682/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 153}\npage_content='Model: Infiniti q50 3.7 Sedan 4D\nYear: 2015\nMiles: 44K miles\nLocation: Erlanger, KY\nPrices: $18,500\nLink: https://www.facebook.com//marketplace/item/1122796235489721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 154}\npage_content='Model: Tesla Model 3\nYear: 2018\nMiles: 33K miles\nLocation: Hamilton, OH\nPrices: $26,999\nLink: https://www.facebook.com//marketplace/item/967578921781014/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 155}\npage_content='Model: Toyota 4runner SR5 Sport Utility 4D\nYear: 2011\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $16,995\nLink: https://www.facebook.com//marketplace/item/1699766200789007/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 156}\npage_content='Model: Cadillac cts Sport Wagon 4D\nYear: 2012\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/296036426928990/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 157}\npage_content='Model: Ford mustang GT Premium Convertible 2D\nYear: 2007\nMiles: 144K miles\nLocation: Batavia, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/837797351747161/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 158}\npage_content='Model: Chevrolet malibu LT Sedan 4D\nYear: 2013\nMiles: 169K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1418060278909190/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 159}\npage_content='Model: Ford fiesta SE Sedan 4D\nYear: 2014\nMiles: 70K miles\nLocation: Cleves, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/1926347357811390/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 160}\npage_content='Model: Audi a6 2.7T Quattro Sedan 4D\nYear: 2003\nMiles: 135K miles\nLocation: Batavia, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1563596657552324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 161}\npage_content='Model: Acura tsx Sedan 4D\nYear: 2010\nMiles: 210K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/478238671460497/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 162}\npage_content='Model: Hyundai elantra Sport Sedan 4D\nYear: 2017\nMiles: 110K miles\nLocation: Cincinnati, OH\nPrices: $3,200\nLink: https://www.facebook.com//marketplace/item/772019378469877/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 163}\npage_content='Model: Lexus ES 350 Sedan 4D\nYear: 2008\nMiles: 161K miles\nLocation: Cincinnati, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/2549958651877636/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 164}\npage_content='Model: Acura tl\nYear: 2004\nMiles: 18K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1201602170981123/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 165}\npage_content='Model: Ford f150 supercrew cab Lariat Pickup 4D 5 1/2 ft\nYear: 2006\nMiles: 149K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/388219000475181/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 166}\npage_content='Model: Mazda mazda3 s Sport Sedan 4D\nYear: 2008\nMiles: 301K miles\nLocation: Fort Thomas, KY\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/1007653207468038/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 167}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 134K miles\nLocation: Fort Mitchell, KY\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/490437083516646/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 168}\npage_content='Model: Toyota sienna XLE Minivan 4D\nYear: 2012\nMiles: 123K miles\nLocation: West Chester, OH\nPrices: $10,995\nLink: https://www.facebook.com//marketplace/item/1651976115603941/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 169}\npage_content='Model: Pontiac g6 gt\nYear: 2009\nMiles: 64K miles\nLocation: Cincinnati, OH\nPrices: $7,800\nLink: https://www.facebook.com//marketplace/item/7973219902745772/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 170}\npage_content='Model: Mazda mazda3\nYear: 2004\nMiles: 203K miles\nLocation: Florence, KY\nPrices: $1,749\nLink: https://www.facebook.com//marketplace/item/986810260115528/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 171}\npage_content='Model: Toyota camry SE Coupe 2D\nYear: 1996\nMiles: 200K miles\nLocation: Florence, KY\nPrices: $700\nLink: https://www.facebook.com//marketplace/item/781400517522902/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 172}\npage_content='Model: Honda civic Sport\nYear: 2024\nMiles: 10K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/1111121573338243/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 173}\npage_content='Model: Honda accord LX Sedan 4D\nYear: 2007\nMiles: 200K miles\nLocation: Cincinnati, OH\nPrices: $2,500\nLink: https://www.facebook.com//marketplace/item/813310967196628/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata

In [80]:
message = ChatMessage(role="user", content=custom_prompt)
response = llm([message])
answer2 = response.content
print(response.content,end='\n')

Based on your criteria, the most suitable car for you would be the 2017 Honda Accord LX Sedan 4D with 77K miles and a price of $6,200. It is located in Latonia, KY and is not from a dealership. You can view the listing here: [Honda Accord](https://www.facebook.com//marketplace/item/839430337752035/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)

In [85]:
max_rows = 120  # Adjust this number based on your needs and the data size
truncated_data = data[2* max_rows: 3 *max_rows]
truncated_data

[Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 240}, page_content='Model: Mazda MAZDASPEED3 Sport Hatchback 4D\nYear: 2007\nMiles: 187K miles\nLocation: Felicity, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/864785834823633/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 241}, page_content='Model: Lexus ES 350 Sedan 4D\nYear: 2008\nMiles: 203K miles\nLocation: Cincinnati, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/25930212356593475/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 242}, page_content='Model: Cadillac cts Sedan 4D\nYear: 2003\nMiles: 109K miles\nLocation: West Chester, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/986727619587351/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 243}, page_content='Model: Chevrolet Aveo5 LS Hatchback Sedan 4D\nYear: 2007\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $2,000\nLink: https://www.facebook.com//marketplace/item/1004621941277484/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 244}, page_content='Model: Pontiac vibe GT Sport Wagon 4D\nYear: 2009\nMiles: 143K miles\nLocation: Loveland, OH\nPrices: $4,995\nLink: https://www.facebook.com//marketplace/item/1133286641109119/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 245}, page_content='Model: Nissan rogue SL Sport Utility 4D\nYear: 2010\nMiles: 163K miles\nLocation: West Chester, OH\nPrices: $6,000\nLink: https://www.facebook.com//marketplace/item/1112572356495564/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 246}, page_content='Model: Honda civic\nYear: 2012\nMiles: 130K miles\nLocation: Covington, KY\nPrices: $6,800\nLink: https://www.facebook.com//marketplace/item/1022908432594457/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 247}, page_content='Model: Hyundai accent gls 4-door\nYear: 2009\nMiles: 161K miles\nLocation: Cincinnati, OH\nPrices: $2,199\nLink: https://www.facebook.com//marketplace/item/475122611774676/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 248}, page_content='Model: Ford fusion SEL Sedan 4D\nYear: 2007\nMiles: 166K miles\nLocation: Cincinnati, OH\nPrices: $1,999\nLink: https://www.facebook.com//marketplace/item/1053442209535590/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 249}, page_content='Model: Mercedes-Benz r-class R 350 4MATIC Sport Wagon 4D\nYear: 2010\nMiles: 195K miles\nLocation: Erlanger, KY\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/470971522184505/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 250}, page_content='Model: Ford ranger regular cab XL Pickup 2D 6 ft\nYear: 2008\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/1000222918230176/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 251}, page_content='Model: Toyota matrix s awd (((fully serviced )))\nYear: 2009\nMiles: 160K miles Â· Dealership\nLocation: Cincinnati, OH\nPrices: $7,495\nLink: https://www.facebook.com//marketplace/item/989028532497124/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 252}, page_content='Model: Saturn ion 2 Sedan 4D\nYear: 2007\nMiles: 120K miles\nLocation: Englewood, OH\nPrices: $2,995\nLink: https://www.facebook.com//marketplace/item/460041063486517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 253}, page_content='Model: Kia soul ! Wagon 4D\nYear: 2016\nMiles: 131K miles\nLocation: Cincinnati, OH\nPrices: $4,250\nLink: https://www.facebook.com//marketplace/item/826376169551552/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 254}, page_content='Model: Jaguar s-type Sedan 4D\nYear: 2004\nMiles: 95K miles\nLocation: Camp Dennison, OH\nPrices: $2,995\nLink: https://www.facebook.com//marketplace/item/505255155258447/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 255}, page_content='Model: Mazda cx-9\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/400209379693341/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 256}, page_content='Model: MINI cooper S Hatchback 2D\nYear: 2008\nMiles: 100K miles\nLocation: Mason, OH\nPrices: $7,000\nLink: https://www.facebook.com//marketplace/item/792700749636370/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 257}, page_content='Model: Subaru forester S Sport Utility 4D\nYear: 2001\nMiles: 65K miles\nLocation: Cincinnati, OH\nPrices: $7,700\nLink: https://www.facebook.com//marketplace/item/993653571622366/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 258}, page_content='Model: Honda civic Si Sedan 4D\nYear: 2017\nMiles: 209K miles\nLocation: New Richmond, OH\nPrices: $7,500\nLink: https://www.facebook.com//marketplace/item/774527764881918/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 259}, page_content='Model: Honda accord hybrid Sedan 4D\nYear: 2014\nMiles: 148K miles\nLocation: Cincinnati, OH\nPrices: $7,300\nLink: https://www.facebook.com//marketplace/item/1000485124970304/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 260}, page_content='Model: Chevrolet trax LT Sport Utility 4D\nYear: 2015\nMiles: 188K miles\nLocation: Cincinnati, OH\nPrices: $3,810\nLink: https://www.facebook.com//marketplace/item/1736195400548540/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 261}, page_content='Model: Buick skylark Gran Sport Coupe 2D\nYear: 1968\nMiles: 77K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/3666023313663527/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 262}, page_content='Model: Mazda mazda3 s Grand Touring Sedan 4D\nYear: 2007\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $950\nLink: https://www.facebook.com//marketplace/item/743298887890366/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 263}, page_content='Model: Ford f-250 Long Bed\nYear: 1964\nMiles: 28K miles\nLocation: Cincinnati, OH\nPrices: $13,500\nLink: https://www.facebook.com//marketplace/item/1429732557912697/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 264}, page_content='Model: Chevrolet\nYear: 1953\nMiles: 6.9K miles\nLocation: Cincinnati, OH\nPrices: $1,000\nLink: https://www.facebook.com//marketplace/item/1041494010962191/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 265}, page_content='Model: Cadillac CTs 4\nYear: 2011\nMiles: 156K miles\nLocation: Maineville, OH\nPrices: $4,950\nLink: https://www.facebook.com//marketplace/item/1132922697784015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 266}, page_content='Model: Infiniti g35x\nYear: 2008\nMiles: 143K miles\nLocation: Cincinnati, OH\nPrices: $4,450\nLink: https://www.facebook.com//marketplace/item/443362038619098/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 267}, page_content='Model: Jeep cherokee TrailHawk Sport Utility 4D\nYear: 2014\nMiles: 85K miles\nLocation: Cincinnati, OH\nPrices: $9,000\nLink: https://www.facebook.com//marketplace/item/249210104912417/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 268}, page_content='Model: Toyota camry XLE Sedan 4D\nYear: 2004\nMiles: 71K miles\nLocation: Middletown, OH\nPrices: $4,950\nLink: https://www.facebook.com//marketplace/item/7984972164874610/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 269}, page_content='Model: Honda civic LX Sedan 4D\nYear: 2017\nMiles: 67K miles\nLocation: Cincinnati, OH\nPrices: $14,900\nLink: https://www.facebook.com//marketplace/item/425412290476577/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 270}, page_content='Model: Hyundai sonata\nYear: 2016\nMiles: 124K miles\nLocation: West Chester, OH\nPrices: $6,400\nLink: https://www.facebook.com//marketplace/item/1035460081254688/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 271}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2010\nMiles: 125K miles\nLocation: Cincinnati, OH\nPrices: $7,999\nLink: https://www.facebook.com//marketplace/item/968413084925313/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 272}, page_content='Model: Mazda mazda3 s Sport Hatchback 4D\nYear: 2008\nMiles: 192K miles\nLocation: Cincinnati, OH\nPrices: $3,995\nLink: https://www.facebook.com//marketplace/item/461387076852985/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 273}, page_content='Model: Honda accord EX-L Sedan 4D\nYear: 2008\nMiles: 198K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/701519122155071/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 274}, page_content='Model: Dodge dart SXT Sedan 4D\nYear: 2015\nMiles: 93K miles\nLocation: Florence, KY\nPrices: $8,000\nLink: https://www.facebook.com//marketplace/item/1614774332635042/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 275}, page_content='Model: Toyota corolla LE Sedan 4D\nYear: 2008\nMiles: 167K miles\nLocation: Harrison, OH\nPrices: $4,600\nLink: https://www.facebook.com//marketplace/item/1177248373587130/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 276}, page_content='Model: Honda accord EX-L Sedan 4D\nYear: 2004\nMiles: 192K miles\nLocation: Cincinnati, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/1530491257808485/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 277}, page_content='Model: Toyota corolla S Sedan 4D\nYear: 2006\nMiles: 132K miles\nLocation: Florence, KY\nPrices: $6,300\nLink: https://www.facebook.com//marketplace/item/502698672160800/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),

In [86]:
# Replace file path in the raw data
cleaned_data = pattern.sub(remove_file_path, formatted_data)
cleaned_data

"page_content='Model: Lexus nx 200t Sport Utility 4D\nYear: 2017\nMiles: 147K miles\nLocation: Cincinnati, OH\nPrices: $17,000\nLink: https://www.facebook.com//marketplace/item/776107654594806/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 120}\npage_content='Model: Ford focus SE Sedan 4D\nYear: 2013\nMiles: 72K miles\nLocation: Fairfield, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1298916234846623/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 121}\npage_content='Model: Porsche cayenne S Sport Utility 4D\nYear: 2004\nMiles: 191K miles\nLocation: Loveland, OH\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/496410932875254/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 122}\npage_content='Model: Volkswagen jetta 2.0L Base Sedan 4D\nYear: 2014\nMiles: 137K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/420549837094259/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 123}\npage_content='Model: Subaru legacy 2.5i Premium Sedan 4D\nYear: 2016\nMiles: 109K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/2654700638041405/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 124}\npage_content='Model: Audi a4 1.8T Quattro Sedan 4D\nYear: 2004\nMiles: 126K miles\nLocation: Hamilton, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1638071446952897/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 125}\npage_content='Model: Toyota corolla S Special Edition Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/1777726666084648/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 126}\npage_content='Model: Toyota yaris Sedan 4D\nYear: 2008\nMiles: 207K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1700483824058284/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 127}\npage_content='Model: Land Rover range rover HSE Sport Utility 4D\nYear: 2005\nMiles: 107K miles Â· Dealership\nLocation: Hamilton, OH\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1533212650955326/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 128}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2008\nMiles: 209K miles\nLocation: Franklin, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1677107559529517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 129}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 112K miles\nLocation: Mason, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/3259807954163150/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 130}\npage_content='Model: Ford focus se\nYear: 2014\nMiles: 202K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/352380731063081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 131}\npage_content='Model: Toyota rav4\nYear: 2000\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/471666759138771/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 132}\npage_content='Model: Chevrolet impala LTZ Sedan 4D\nYear: 2014\nMiles: 123K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/400141629708545/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 133}\npage_content='Model: Buick le sabre Custom\nYear: 2001\nMiles: 13K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/3781756528729362/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 134}\npage_content='Model: Acura ILX\nYear: 2019\nMiles: 43K miles\nLocation: Cincinnati, OH\nPrices: $14,500\nLink: https://www.facebook.com//marketplace/item/1005138321050008/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 135}\npage_content='Model: Nissan altima 2.5 Sedan 4D\nYear: 2010\nMiles: 165K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/801142051804133/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 136}\npage_content='Model: Toyota corolla\nYear: 2013\nMiles: 400 miles\nLocation: Cincinnati, OH\nPrices: $8,990\nLink: https://www.facebook.com//marketplace/item/438386274719003/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 137}\npage_content='Model: Nissan versa\nYear: 2009\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1037957944613175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 138}\npage_content='Model: Hyundai sonata Sedan 4D\nYear: 2003\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $2,399\nLink: https://www.facebook.com//marketplace/item/1720260141839755/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 139}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 111K miles\nLocation: Fairfield, OH\nPrices: $9,850\nLink: https://www.facebook.com//marketplace/item/8207611969291247/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 140}\npage_content='Model: Nissan versa SL Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1132833847775834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 141}\npage_content='Model: Genesis g90 5.0 Ultimate Sedan 4D\nYear: 2021\nMiles: 22K miles\nLocation: Cincinnati, OH\nPrices: $51,118\nLink: https://www.facebook.com//marketplace/item/670265935284890/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 142}\npage_content='Model: Toyota prius One Hatchback 4D\nYear: 2015\nMiles: 111K miles\nLocation: Cincinnati, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/1371683937563859/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 143}\npage_content='Model: Lexus IS 350 Sport Sedan 4D\nYear: 2008\nMiles: 237K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/726398496192253/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 144}\npage_content='Model: Chevrolet camaro LT Coupe 2D\nYear: 2012\nMiles: 108K miles\nLocation: Cincinnati, OH\nPrices: $7,200\nLink: https://www.facebook.com//marketplace/item/427355033049294/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 145}\npage_content='Model: Toyota matrix S Sport Wagon 4D\nYear: 2009\nMiles: 148K miles\nLocation: Burlington, KY\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/791749699752081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 146}\npage_content='Model: Mitsubishi lancer GTS Sedan 4D\nYear: 2010\nMiles: 162K miles\nLocation: Fort Mitchell, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/2215689042128543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 147}\npage_content='Model: Chevrolet cruze LTZ Sedan 4D\nYear: 2015\nMiles: 113K miles\nLocation: Hebron, KY\nPrices: $123,456\nLink: https://www.facebook.com//marketplace/item/1401954563795275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 148}\npage_content='Model: Honda crosstour EX-L Sport Utility 4D\nYear: 2012\nMiles: 153K miles\nLocation: Hamilton, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/987605822872560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 149}\npage_content='Model: Chevrolet impala LT Sedan 4D\nYear: 2014\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/734720935354670/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 150}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2007\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/833731498698015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 151}\npage_content='Model: Mazda mazda6 s Sedan 4D\nYear: 2003\nMiles: 204K miles\nLocation: Cincinnati, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/3684694805134214/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 152}\npage_content='Model: Hyundai tiburon GS Coupe 2D\nYear: 2006\nMiles: 123K miles\nLocation: Fairfield, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/1013458523831682/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 153}\npage_content='Model: Infiniti q50 3.7 Sedan 4D\nYear: 2015\nMiles: 44K miles\nLocation: Erlanger, KY\nPrices: $18,500\nLink: https://www.facebook.com//marketplace/item/1122796235489721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 154}\npage_content='Model: Tesla Model 3\nYear: 2018\nMiles: 33K miles\nLocation: Hamilton, OH\nPrices: $26,999\nLink: https://www.facebook.com//marketplace/item/967578921781014/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 155}\npage_content='Model: Toyota 4runner SR5 Sport Utility 4D\nYear: 2011\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $16,995\nLink: https://www.facebook.com//marketplace/item/1699766200789007/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 156}\npage_content='Model: Cadillac cts Sport Wagon 4D\nYear: 2012\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/296036426928990/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 157}\npage_content='Model: Ford mustang GT Premium Convertible 2D\nYear: 2007\nMiles: 144K miles\nLocation: Batavia, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/837797351747161/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 158}\npage_content='Model: Chevrolet malibu LT Sedan 4D\nYear: 2013\nMiles: 169K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1418060278909190/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 159}\npage_content='Model: Ford fiesta SE Sedan 4D\nYear: 2014\nMiles: 70K miles\nLocation: Cleves, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/1926347357811390/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 160}\npage_content='Model: Audi a6 2.7T Quattro Sedan 4D\nYear: 2003\nMiles: 135K miles\nLocation: Batavia, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1563596657552324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 161}\npage_content='Model: Acura tsx Sedan 4D\nYear: 2010\nMiles: 210K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/478238671460497/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 162}\npage_content='Model: Hyundai elantra Sport Sedan 4D\nYear: 2017\nMiles: 110K miles\nLocation: Cincinnati, OH\nPrices: $3,200\nLink: https://www.facebook.com//marketplace/item/772019378469877/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 163}\npage_content='Model: Lexus ES 350 Sedan 4D\nYear: 2008\nMiles: 161K miles\nLocation: Cincinnati, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/2549958651877636/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 164}\npage_content='Model: Acura tl\nYear: 2004\nMiles: 18K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1201602170981123/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 165}\npage_content='Model: Ford f150 supercrew cab Lariat Pickup 4D 5 1/2 ft\nYear: 2006\nMiles: 149K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/388219000475181/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 166}\npage_content='Model: Mazda mazda3 s Sport Sedan 4D\nYear: 2008\nMiles: 301K miles\nLocation: Fort Thomas, KY\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/1007653207468038/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 167}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 134K miles\nLocation: Fort Mitchell, KY\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/490437083516646/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 168}\npage_content='Model: Toyota sienna XLE Minivan 4D\nYear: 2012\nMiles: 123K miles\nLocation: West Chester, OH\nPrices: $10,995\nLink: https://www.facebook.com//marketplace/item/1651976115603941/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 169}\npage_content='Model: Pontiac g6 gt\nYear: 2009\nMiles: 64K miles\nLocation: Cincinnati, OH\nPrices: $7,800\nLink: https://www.facebook.com//marketplace/item/7973219902745772/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 170}\npage_content='Model: Mazda mazda3\nYear: 2004\nMiles: 203K miles\nLocation: Florence, KY\nPrices: $1,749\nLink: https://www.facebook.com//marketplace/item/986810260115528/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 171}\npage_content='Model: Toyota camry SE Coupe 2D\nYear: 1996\nMiles: 200K miles\nLocation: Florence, KY\nPrices: $700\nLink: https://www.facebook.com//marketplace/item/781400517522902/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 172}\npage_content='Model: Honda civic Sport\nYear: 2024\nMiles: 10K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/1111121573338243/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 173}\npage_content='Model: Honda accord LX Sedan 4D\nYear: 2007\nMiles: 200K miles\nLocation: Cincinnati, OH\nPrices: $2,500\nLink: https://www.facebook.com//marketplace/item/813310967196628/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata

In [87]:
message = ChatMessage(role="user", content=custom_prompt)
response = llm([message])
answer3 = response.content
print(response.content,end='\n')

Based on your criteria, the most suitable car for you would be the Toyota Camry SE Nightshade Edition Sedan 4D from 2020 with 42K miles and a price of $24,799. It is located in Batavia, OH and does not mention being sold by a dealership.

Link: [Toyota Camry SE Nightshade Edition](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)

In [88]:
len(data)

679

In [89]:
max_rows = 120  # Adjust this number based on your needs and the data size
truncated_data = data[3* max_rows: 4 *max_rows]
truncated_data

[Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 360}, page_content='Model: Dodge caliber SXT Sport Wagon 4D\nYear: 2009\nMiles: 158K miles\nLocation: Cincinnati, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1017170009769560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 361}, page_content='Model: Nissan sentra SE-R Sedan 4D\nYear: 2010\nMiles: 124K miles\nLocation: Cincinnati, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/1189926298803033/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 362}, page_content='Model: Kia rio\nYear: 2013\nMiles: 177K miles\nLocation: Cincinnati, OH\nPrices: $3,700\nLink: https://www.facebook.com//marketplace/item/1219421069060647/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 363}, page_content='Model: Ford mustang\nYear: 2006\nMiles: 121K miles\nLocation: Fairfield, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/800689078797712/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 364}, page_content='Model: Subaru impreza wagon awd 2.0l h4\nYear: 2014\nMiles: 63K miles\nLocation: Cincinnati, OH\nPrices: $12,993\nLink: https://www.facebook.com//marketplace/item/1166179894625471/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 365}, page_content='Model: GMC terrain slt fwd 1.4l l4 turbo\nYear: 2019\nMiles: 85K miles\nLocation: Cincinnati, OH\nPrices: $15,493\nLink: https://www.facebook.com//marketplace/item/3573239966319993/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 366}, page_content='Model: Lexus RX 350 Sport Utility 4D\nYear: 2013\nMiles: 108K miles\nLocation: Hamilton, OH\nPrices: $14,799\nLink: https://www.facebook.com//marketplace/item/1155065715701113/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 367}, page_content='Model: Saturn sky redline turbo\nYear: 2007\nMiles: 48K miles\nLocation: Latonia, KY\nPrices: $16,900\nLink: https://www.facebook.com//marketplace/item/993118325456823/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 368}, page_content='Model: Hyundai accent\nYear: 2016\nMiles: 110K miles\nLocation: Blanchester, OH\nPrices: $5,700\nLink: https://www.facebook.com//marketplace/item/1019697986342955/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 369}, page_content='Model: Toyota rav4 Sport SUV 4D\nYear: 2007\nMiles: 151K miles\nLocation: Fort Mitchell, KY\nPrices: $6,200\nLink: https://www.facebook.com//marketplace/item/399620885865240/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 370}, page_content='Model: Pontiac vibe GT Sport Wagon 4D\nYear: 2009\nMiles: 90K miles\nLocation: Springfield, OH\nPrices: $7,000\nLink: https://www.facebook.com//marketplace/item/362148303220071/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 371}, page_content='Model: Jeep compass\nYear: 2019\nMiles: 75K miles\nLocation: Hamilton, OH\nPrices: $14,999\nLink: https://www.facebook.com//marketplace/item/788034333514548/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 372}, page_content='Model: Chevrolet sonic LT Sedan 4D\nYear: 2013\nMiles: 170K miles\nLocation: Cincinnati, OH\nPrices: $2,500\nLink: https://www.facebook.com//marketplace/item/3629363420710161/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 373}, page_content='Model: Audi a8 L Quattro Sedan 4D\nYear: 2009\nMiles: 160K miles\nLocation: South Lebanon, OH\nPrices: $6,000\nLink: https://www.facebook.com//marketplace/item/361572633634861/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 374}, page_content='Model: Ford crown victoria\nYear: 2010\nMiles: 150K miles\nLocation: Hamilton, OH\nPrices: $1,400\nLink: https://www.facebook.com//marketplace/item/811043060808809/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 375}, page_content='Model: Kia spectru\nYear: 2004\nMiles: 227K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/492928663135954/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 376}, page_content='Model: Dodge caliber\nYear: 2011\nMiles: 127K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/1144176923332883/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 377}, page_content='Model: Mitsubishi eclipse GTS Spyder Convertible 2D\nYear: 2004\nMiles: 149K miles\nLocation: Cincinnati, OH\nPrices: $2,200\nLink: https://www.facebook.com//marketplace/item/421018857605704/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 378}, page_content='Model: Chrysler 300C Sedan 4D\nYear: 2005\nMiles: 140K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/325375280640025/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 379}, page_content='Model: Nissan maxima S Sedan 4D\nYear: 2009\nMiles: 233K miles\nLocation: Cincinnati, OH\nPrices: $2,000\nLink: https://www.facebook.com//marketplace/item/443923481820310/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 380}, page_content='Model: Pontiac g6 Sedan 4D\nYear: 2008\nMiles: 154K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/1492147341665718/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 381}, page_content='Model: Chevrolet malibu LT Sedan 4D\nYear: 2008\nMiles: 183K miles\nLocation: Cincinnati, OH\nPrices: $2,500\nLink: https://www.facebook.com//marketplace/item/363077599799684/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 382}, page_content='Model: Toyota prius Hybrid\nYear: 2008\nMiles: 223K miles\nLocation: Fort Mitchell, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/1621370591874561/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 383}, page_content='Model: Mitsubishi outlander sport ES Sport Utility 4D\nYear: 2014\nMiles: 194K miles\nLocation: West Harrison, IN\nPrices: $2,000\nLink: https://www.facebook.com//marketplace/item/988181409457624/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 384}, page_content='Model: Toyota pickup 4x4\nYear: 1989\nMiles: 125K miles\nLocation: Cincinnati, OH\nPrices: $12,500\nLink: https://www.facebook.com//marketplace/item/1227521198603341/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 385}, page_content='Model: Dodge caliber SE Sport Wagon 4D\nYear: 2008\nMiles: 139K miles\nLocation: Lawrenceburg, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/956227782921248/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 386}, page_content='Model: Cadillac sts\nYear: 2008\nMiles: 44K miles\nLocation: Hamilton, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/8115007705228174/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 387}, page_content='Model: Lexus RX 330 Sport Utility 4D\nYear: 2005\nMiles: 207K miles\nLocation: Batavia, OH\nPrices: $4,800\nLink: https://www.facebook.com//marketplace/item/857631912888489/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 388}, page_content='Model: Chevrolet malibu LT Sedan 4D\nYear: 2015\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/798445825691048/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 389}, page_content='Model: Ford mustang Coupe 2D\nYear: 2000\nMiles: 117K miles\nLocation: Cincinnati, OH\nPrices: $2,800\nLink: https://www.facebook.com//marketplace/item/841212244450303/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 390}, page_content='Model: Hyundai santa fe GLS Sport Utility 4D\nYear: 2002\nMiles: 253K miles\nLocation: Cleves, OH\nPrices: $1,700\nLink: https://www.facebook.com//marketplace/item/2149014715468972/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 391}, page_content='Model: Chevrolet traverse\nYear: 2018\nMiles: 94K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1606704246846144/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 392}, page_content='Model: Honda odyssey touring fwd 3.5l v6\nYear: 2014\nMiles: 114K miles\nLocation: Cincinnati, OH\nPrices: $13,993\nLink: https://www.facebook.com//marketplace/item/698629295742196/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 393}, page_content='Model: Volkswagen passat Sedan 4D\nYear: 2007\nMiles: 120K miles\nLocation: Cincinnati, OH\nPrices: $1\nLink: https://www.facebook.com//marketplace/item/462000836581894/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 394}, page_content='Model: Toyota tundra access cab SR5 Pickup 4D 6 1/2 ft\nYear: 2000\nMiles: 200K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/452144660766532/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 395}, page_content='Model: Ford thunderbird Sport Coupe 2D\nYear: 1966\nMiles: 123K miles\nLocation: North Bend, OH\nPrices: $2,200\nLink: https://www.facebook.com//marketplace/item/985285329906959/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 396}, page_content='Model: Chevrolet equinox\nYear: 2018\nMiles: 92K miles\nLocation: Cincinnati, OH\nPrices: $6,000\nLink: https://www.facebook.com//marketplace/item/1189639048719552/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 397}, page_content='Model: Ford escape\nYear: 2011\nMiles: 156K miles\nLocation: Cincinnati, OH\nPrices: $4,450\nLink: https://www.facebook.com//marketplace/item/830549035410858/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),

In [90]:
# Replace file path in the raw data
cleaned_data = pattern.sub(remove_file_path, formatted_data)
cleaned_data

"page_content='Model: Lexus nx 200t Sport Utility 4D\nYear: 2017\nMiles: 147K miles\nLocation: Cincinnati, OH\nPrices: $17,000\nLink: https://www.facebook.com//marketplace/item/776107654594806/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 120}\npage_content='Model: Ford focus SE Sedan 4D\nYear: 2013\nMiles: 72K miles\nLocation: Fairfield, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1298916234846623/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 121}\npage_content='Model: Porsche cayenne S Sport Utility 4D\nYear: 2004\nMiles: 191K miles\nLocation: Loveland, OH\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/496410932875254/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 122}\npage_content='Model: Volkswagen jetta 2.0L Base Sedan 4D\nYear: 2014\nMiles: 137K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/420549837094259/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 123}\npage_content='Model: Subaru legacy 2.5i Premium Sedan 4D\nYear: 2016\nMiles: 109K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/2654700638041405/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 124}\npage_content='Model: Audi a4 1.8T Quattro Sedan 4D\nYear: 2004\nMiles: 126K miles\nLocation: Hamilton, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1638071446952897/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 125}\npage_content='Model: Toyota corolla S Special Edition Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/1777726666084648/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 126}\npage_content='Model: Toyota yaris Sedan 4D\nYear: 2008\nMiles: 207K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1700483824058284/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 127}\npage_content='Model: Land Rover range rover HSE Sport Utility 4D\nYear: 2005\nMiles: 107K miles Â· Dealership\nLocation: Hamilton, OH\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1533212650955326/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 128}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2008\nMiles: 209K miles\nLocation: Franklin, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1677107559529517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 129}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 112K miles\nLocation: Mason, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/3259807954163150/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 130}\npage_content='Model: Ford focus se\nYear: 2014\nMiles: 202K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/352380731063081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 131}\npage_content='Model: Toyota rav4\nYear: 2000\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/471666759138771/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 132}\npage_content='Model: Chevrolet impala LTZ Sedan 4D\nYear: 2014\nMiles: 123K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/400141629708545/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 133}\npage_content='Model: Buick le sabre Custom\nYear: 2001\nMiles: 13K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/3781756528729362/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 134}\npage_content='Model: Acura ILX\nYear: 2019\nMiles: 43K miles\nLocation: Cincinnati, OH\nPrices: $14,500\nLink: https://www.facebook.com//marketplace/item/1005138321050008/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 135}\npage_content='Model: Nissan altima 2.5 Sedan 4D\nYear: 2010\nMiles: 165K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/801142051804133/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 136}\npage_content='Model: Toyota corolla\nYear: 2013\nMiles: 400 miles\nLocation: Cincinnati, OH\nPrices: $8,990\nLink: https://www.facebook.com//marketplace/item/438386274719003/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 137}\npage_content='Model: Nissan versa\nYear: 2009\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1037957944613175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 138}\npage_content='Model: Hyundai sonata Sedan 4D\nYear: 2003\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $2,399\nLink: https://www.facebook.com//marketplace/item/1720260141839755/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 139}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 111K miles\nLocation: Fairfield, OH\nPrices: $9,850\nLink: https://www.facebook.com//marketplace/item/8207611969291247/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 140}\npage_content='Model: Nissan versa SL Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1132833847775834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 141}\npage_content='Model: Genesis g90 5.0 Ultimate Sedan 4D\nYear: 2021\nMiles: 22K miles\nLocation: Cincinnati, OH\nPrices: $51,118\nLink: https://www.facebook.com//marketplace/item/670265935284890/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 142}\npage_content='Model: Toyota prius One Hatchback 4D\nYear: 2015\nMiles: 111K miles\nLocation: Cincinnati, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/1371683937563859/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 143}\npage_content='Model: Lexus IS 350 Sport Sedan 4D\nYear: 2008\nMiles: 237K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/726398496192253/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 144}\npage_content='Model: Chevrolet camaro LT Coupe 2D\nYear: 2012\nMiles: 108K miles\nLocation: Cincinnati, OH\nPrices: $7,200\nLink: https://www.facebook.com//marketplace/item/427355033049294/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 145}\npage_content='Model: Toyota matrix S Sport Wagon 4D\nYear: 2009\nMiles: 148K miles\nLocation: Burlington, KY\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/791749699752081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 146}\npage_content='Model: Mitsubishi lancer GTS Sedan 4D\nYear: 2010\nMiles: 162K miles\nLocation: Fort Mitchell, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/2215689042128543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 147}\npage_content='Model: Chevrolet cruze LTZ Sedan 4D\nYear: 2015\nMiles: 113K miles\nLocation: Hebron, KY\nPrices: $123,456\nLink: https://www.facebook.com//marketplace/item/1401954563795275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 148}\npage_content='Model: Honda crosstour EX-L Sport Utility 4D\nYear: 2012\nMiles: 153K miles\nLocation: Hamilton, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/987605822872560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 149}\npage_content='Model: Chevrolet impala LT Sedan 4D\nYear: 2014\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/734720935354670/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 150}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2007\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/833731498698015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 151}\npage_content='Model: Mazda mazda6 s Sedan 4D\nYear: 2003\nMiles: 204K miles\nLocation: Cincinnati, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/3684694805134214/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 152}\npage_content='Model: Hyundai tiburon GS Coupe 2D\nYear: 2006\nMiles: 123K miles\nLocation: Fairfield, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/1013458523831682/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 153}\npage_content='Model: Infiniti q50 3.7 Sedan 4D\nYear: 2015\nMiles: 44K miles\nLocation: Erlanger, KY\nPrices: $18,500\nLink: https://www.facebook.com//marketplace/item/1122796235489721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 154}\npage_content='Model: Tesla Model 3\nYear: 2018\nMiles: 33K miles\nLocation: Hamilton, OH\nPrices: $26,999\nLink: https://www.facebook.com//marketplace/item/967578921781014/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 155}\npage_content='Model: Toyota 4runner SR5 Sport Utility 4D\nYear: 2011\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $16,995\nLink: https://www.facebook.com//marketplace/item/1699766200789007/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 156}\npage_content='Model: Cadillac cts Sport Wagon 4D\nYear: 2012\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/296036426928990/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 157}\npage_content='Model: Ford mustang GT Premium Convertible 2D\nYear: 2007\nMiles: 144K miles\nLocation: Batavia, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/837797351747161/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 158}\npage_content='Model: Chevrolet malibu LT Sedan 4D\nYear: 2013\nMiles: 169K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1418060278909190/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 159}\npage_content='Model: Ford fiesta SE Sedan 4D\nYear: 2014\nMiles: 70K miles\nLocation: Cleves, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/1926347357811390/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 160}\npage_content='Model: Audi a6 2.7T Quattro Sedan 4D\nYear: 2003\nMiles: 135K miles\nLocation: Batavia, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1563596657552324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 161}\npage_content='Model: Acura tsx Sedan 4D\nYear: 2010\nMiles: 210K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/478238671460497/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 162}\npage_content='Model: Hyundai elantra Sport Sedan 4D\nYear: 2017\nMiles: 110K miles\nLocation: Cincinnati, OH\nPrices: $3,200\nLink: https://www.facebook.com//marketplace/item/772019378469877/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 163}\npage_content='Model: Lexus ES 350 Sedan 4D\nYear: 2008\nMiles: 161K miles\nLocation: Cincinnati, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/2549958651877636/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 164}\npage_content='Model: Acura tl\nYear: 2004\nMiles: 18K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1201602170981123/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 165}\npage_content='Model: Ford f150 supercrew cab Lariat Pickup 4D 5 1/2 ft\nYear: 2006\nMiles: 149K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/388219000475181/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 166}\npage_content='Model: Mazda mazda3 s Sport Sedan 4D\nYear: 2008\nMiles: 301K miles\nLocation: Fort Thomas, KY\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/1007653207468038/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 167}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 134K miles\nLocation: Fort Mitchell, KY\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/490437083516646/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 168}\npage_content='Model: Toyota sienna XLE Minivan 4D\nYear: 2012\nMiles: 123K miles\nLocation: West Chester, OH\nPrices: $10,995\nLink: https://www.facebook.com//marketplace/item/1651976115603941/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 169}\npage_content='Model: Pontiac g6 gt\nYear: 2009\nMiles: 64K miles\nLocation: Cincinnati, OH\nPrices: $7,800\nLink: https://www.facebook.com//marketplace/item/7973219902745772/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 170}\npage_content='Model: Mazda mazda3\nYear: 2004\nMiles: 203K miles\nLocation: Florence, KY\nPrices: $1,749\nLink: https://www.facebook.com//marketplace/item/986810260115528/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 171}\npage_content='Model: Toyota camry SE Coupe 2D\nYear: 1996\nMiles: 200K miles\nLocation: Florence, KY\nPrices: $700\nLink: https://www.facebook.com//marketplace/item/781400517522902/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 172}\npage_content='Model: Honda civic Sport\nYear: 2024\nMiles: 10K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/1111121573338243/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 173}\npage_content='Model: Honda accord LX Sedan 4D\nYear: 2007\nMiles: 200K miles\nLocation: Cincinnati, OH\nPrices: $2,500\nLink: https://www.facebook.com//marketplace/item/813310967196628/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata

In [91]:
message = ChatMessage(role="user", content=custom_prompt)
response = llm([message])
answer4 = response.content
print(response.content,end='\n')

Based on your criteria, the most suitable car for you would be the Toyota Camry SE Nightshade Edition Sedan 4D from 2020 with 42K miles priced at $24,799. It is a newer model with low mileage and fits your preferences for Toyota.

Here is the link to the listing: [Toyota Camry SE Nightshade Edition](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)

This car meets all your criteria as it is a Toyota, has low mileage, is a newer model, and is not from a dealership.

In [92]:
max_rows = 120  # Adjust this number based on your needs and the data size
truncated_data = data[4* max_rows: len(data)]
truncated_data

[Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 480}, page_content='Model: Audi s6 Sedan 4D\nYear: 2014\nMiles: 107K miles\nLocation: Cincinnati, OH\nPrices: $16,000\nLink: https://www.facebook.com//marketplace/item/2569477653211978/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 481}, page_content='Model: Chevrolet spark 2LT Hatchback 4D\nYear: 2014\nMiles: 151K miles\nLocation: Fairfield, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/5194789440570407/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 482}, page_content='Model: Toyota camry CE Sedan 4D\nYear: 1999\nMiles: 96K miles Â· Dealership\nLocation: Franklin, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/1500158697243368/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 483}, page_content='Model: Toyota corolla\nYear: 2016\nMiles: 94K miles\nLocation: Cincinnati, OH\nPrices: $10,000\nLink: https://www.facebook.com//marketplace/item/1921619578287068/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 484}, page_content='Model: Mazda cx-5 Grand Touring Sport Utility 4D\nYear: 2015\nMiles: 95K miles\nLocation: Maineville, OH\nPrices: $15,800\nLink: https://www.facebook.com//marketplace/item/450606384558787/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 485}, page_content='Model: Hyundai elantra SEL Sedan 4D\nYear: 2021\nMiles: 41K miles\nLocation: Bethel, OH\nPrices: $19,500\nLink: https://www.facebook.com//marketplace/item/987427496120235/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 486}, page_content='Model: Hyundai santa fe sport Sport Utility 4D\nYear: 2016\nMiles: 155K miles\nLocation: Hamilton, OH\nPrices: $7,500\nLink: https://www.facebook.com//marketplace/item/997170885326742/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 487}, page_content='Model: Mazda mazda6 i Touring Sedan 4D\nYear: 2010\nMiles: 84K miles\nLocation: Loveland, OH\nPrices: $6,500\nLink: https://www.facebook.com//marketplace/item/480211561261973/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 488}, page_content='Model: Toyota corolla S Sedan 4D\nYear: 2014\nMiles: 187K miles Â· Dealership\nLocation: Fairfield, OH\nPrices: $7,900\nLink: https://www.facebook.com//marketplace/item/444814315061975/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 489}, page_content='Model: Mazda mazda3 s Sport Hatchback 4D\nYear: 2008\nMiles: 200K miles Â· Dealership\nLocation: Cincinnati, OH\nPrices: $2,800\nLink: https://www.facebook.com//marketplace/item/975946034211856/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 490}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2010\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1332715654783469/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 491}, page_content='Model: Hyundai elantra SEL Sedan 4D\nYear: 2021\nMiles: 53K miles\nLocation: Cincinnati, OH\nPrices: $18,000\nLink: https://www.facebook.com//marketplace/item/310850075293121/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 492}, page_content='Model: Toyota camry SE Sedan 4D\nYear: 2009\nMiles: 198K miles\nLocation: Cincinnati, OH\nPrices: $4,499\nLink: https://www.facebook.com//marketplace/item/3440427696249904/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 493}, page_content='Model: Chevrolet cruze diesel\nYear: 2014\nMiles: 77K miles\nLocation: Harrison, OH\nPrices: $10,500\nLink: https://www.facebook.com//marketplace/item/839038361075175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 494}, page_content='Model: Toyota camry LE Sedan 4D\nYear: 2012\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $7,000\nLink: https://www.facebook.com//marketplace/item/851510533705064/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 495}, page_content='Model: Honda civic LX Sedan 4D\nYear: 2014\nMiles: 140K miles\nLocation: Hamilton, OH\nPrices: $7,500\nLink: https://www.facebook.com//marketplace/item/995821988907144/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 496}, page_content='Model: Honda accord ex-l\nYear: 2009\nMiles: 155K miles\nLocation: Covington, KY\nPrices: $6,900\nLink: https://www.facebook.com//marketplace/item/776365741029035/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 497}, page_content='Model: Hyundai sonata hybrid\nYear: 2015\nMiles: 112K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/1144599193523391/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 498}, page_content='Model: Mazda mazda6 i Sport Sedan 4D\nYear: 2011\nMiles: 176K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/1079963933013391/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 499}, page_content='Model: Ford fiesta SE Sedan 4D\nYear: 2012\nMiles: 135K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/998741315233459/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 500}, page_content='Model: Toyota camry\nYear: 2009\nMiles: 110K miles\nLocation: Cincinnati, OH\nPrices: $6,900\nLink: https://www.facebook.com//marketplace/item/1422366301818556/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 501}, page_content='Model: BMW 3 series\nYear: 2011\nMiles: 40K miles\nLocation: West Chester, OH\nPrices: $14,995\nLink: https://www.facebook.com//marketplace/item/1555626398354508/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 502}, page_content='Model: Ford transit Good condition\nYear: 2013\nMiles: 160K miles\nLocation: Fairfield, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/1568108066975244/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 503}, page_content='Model: Ford focus SE Hatchback 4D\nYear: 2016\nMiles: 105K miles\nLocation: Hamilton, OH\nPrices: $4,950\nLink: https://www.facebook.com//marketplace/item/3618074858458129/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 504}, page_content='Model: Honda civic EX Coupe 2D\nYear: 2012\nMiles: 212K miles\nLocation: West Chester, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1719371828849276/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 505}, page_content='Model: Honda accord EX-L Sedan 4D\nYear: 2011\nMiles: 194K miles\nLocation: Cincinnati, OH\nPrices: $5,499\nLink: https://www.facebook.com//marketplace/item/3714373055470963/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 506}, page_content='Model: Honda fit LX Hatchback 4D\nYear: 2017\nMiles: 8.5K miles\nLocation: Hamilton, OH\nPrices: $8,800\nLink: https://www.facebook.com//marketplace/item/1149721253003443/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 507}, page_content='Model: Nissan altima !!!down payment!!!\nYear: 2019\nMiles: 105K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/397440406357580/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 508}, page_content='Model: Volkswagen jetta TDI SportWagen Sport Wagon 4D\nYear: 2011\nMiles: 120K miles\nLocation: Georgetown, KY\nPrices: $3,900\nLink: https://www.facebook.com//marketplace/item/839007427777065/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 509}, page_content='Model: Honda accord EX Sedan 4D\nYear: 2007\nMiles: 373K miles\nLocation: Florence, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/383407031516418/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 510}, page_content='Model: Honda civic Sport Hatchback 4D\nYear: 2017\nMiles: 158K miles\nLocation: Fairfield, OH\nPrices: $11,250\nLink: https://www.facebook.com//marketplace/item/803750278520001/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 511}, page_content='Model: Lexus ES 350 Sedan 4D\nYear: 2010\nMiles: 203K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/2261737647496437/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 512}, page_content='Model: Honda accord Sport Sedan 4D\nYear: 2018\nMiles: 70K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/1241239310378487/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 513}, page_content='Model: Nissan versa S Sedan 4D\nYear: 2012\nMiles: 151K miles\nLocation: Harrison, OH\nPrices: $3,400\nLink: https://www.facebook.com//marketplace/item/1074642090748688/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 514}, page_content='Model: Toyota matrix XRS Sport Wagon 4D\nYear: 2009\nMiles: 170K miles\nLocation: Cincinnati, OH\nPrices: $3,200\nLink: https://www.facebook.com//marketplace/item/1225598018852559/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 515}, page_content='Model: Ford mustang\nYear: 2011\nMiles: 110K miles\nLocation: Middletown, OH\nPrices: $6,900\nLink: https://www.facebook.com//marketplace/item/7787543637988716/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 516}, page_content='Model: Subaru outback Wilderness Wagon 4D\nYear: 2022\nMiles: 39K km\nLocation: Union, KY\nPrices: â‚¬38,000\nLink: https://www.facebook.com//marketplace/item/2189078758109807/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),
 Document(metadata={'source': 'C:\\Users\\gauur\\projects\\Fifth Third\\finale_fidelity\\Car_Price_Facebook_Marketpalce\\datasets\\2024-07-10-Cincinnati-Ohio.csv', 'row': 517}, page_content='Model: Ford fusion SEL Sedan 4D\nYear: 2006\nMiles: 104K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1055988132767149/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10'),

In [93]:
# Replace file path in the raw data
cleaned_data = pattern.sub(remove_file_path, formatted_data)
cleaned_data

"page_content='Model: Lexus nx 200t Sport Utility 4D\nYear: 2017\nMiles: 147K miles\nLocation: Cincinnati, OH\nPrices: $17,000\nLink: https://www.facebook.com//marketplace/item/776107654594806/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 120}\npage_content='Model: Ford focus SE Sedan 4D\nYear: 2013\nMiles: 72K miles\nLocation: Fairfield, OH\nPrices: $4,850\nLink: https://www.facebook.com//marketplace/item/1298916234846623/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 121}\npage_content='Model: Porsche cayenne S Sport Utility 4D\nYear: 2004\nMiles: 191K miles\nLocation: Loveland, OH\nPrices: $5,600\nLink: https://www.facebook.com//marketplace/item/496410932875254/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 122}\npage_content='Model: Volkswagen jetta 2.0L Base Sedan 4D\nYear: 2014\nMiles: 137K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/420549837094259/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 123}\npage_content='Model: Subaru legacy 2.5i Premium Sedan 4D\nYear: 2016\nMiles: 109K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/2654700638041405/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 124}\npage_content='Model: Audi a4 1.8T Quattro Sedan 4D\nYear: 2004\nMiles: 126K miles\nLocation: Hamilton, OH\nPrices: $3,800\nLink: https://www.facebook.com//marketplace/item/1638071446952897/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 125}\npage_content='Model: Toyota corolla S Special Edition Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $9,500\nLink: https://www.facebook.com//marketplace/item/1777726666084648/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 126}\npage_content='Model: Toyota yaris Sedan 4D\nYear: 2008\nMiles: 207K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/1700483824058284/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 127}\npage_content='Model: Land Rover range rover HSE Sport Utility 4D\nYear: 2005\nMiles: 107K miles Â· Dealership\nLocation: Hamilton, OH\nPrices: $5,950\nLink: https://www.facebook.com//marketplace/item/1533212650955326/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 128}\npage_content='Model: Toyota camry SE Sedan 4D\nYear: 2008\nMiles: 209K miles\nLocation: Franklin, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1677107559529517/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 129}\npage_content='Model: Chrysler 200 Touring Sedan 4D\nYear: 2013\nMiles: 112K miles\nLocation: Mason, OH\nPrices: $3,999\nLink: https://www.facebook.com//marketplace/item/3259807954163150/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 130}\npage_content='Model: Ford focus se\nYear: 2014\nMiles: 202K miles\nLocation: Covington, KY\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/352380731063081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 131}\npage_content='Model: Toyota rav4\nYear: 2000\nMiles: 100K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/471666759138771/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 132}\npage_content='Model: Chevrolet impala LTZ Sedan 4D\nYear: 2014\nMiles: 123K miles\nLocation: Cincinnati, OH\nPrices: $8,999\nLink: https://www.facebook.com//marketplace/item/400141629708545/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 133}\npage_content='Model: Buick le sabre Custom\nYear: 2001\nMiles: 13K miles\nLocation: Cincinnati, OH\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/3781756528729362/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 134}\npage_content='Model: Acura ILX\nYear: 2019\nMiles: 43K miles\nLocation: Cincinnati, OH\nPrices: $14,500\nLink: https://www.facebook.com//marketplace/item/1005138321050008/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 135}\npage_content='Model: Nissan altima 2.5 Sedan 4D\nYear: 2010\nMiles: 165K miles\nLocation: Cincinnati, OH\nPrices: $3,000\nLink: https://www.facebook.com//marketplace/item/801142051804133/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 136}\npage_content='Model: Toyota corolla\nYear: 2013\nMiles: 400 miles\nLocation: Cincinnati, OH\nPrices: $8,990\nLink: https://www.facebook.com//marketplace/item/438386274719003/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 137}\npage_content='Model: Nissan versa\nYear: 2009\nMiles: 129K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1037957944613175/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 138}\npage_content='Model: Hyundai sonata Sedan 4D\nYear: 2003\nMiles: 146K miles\nLocation: Cincinnati, OH\nPrices: $2,399\nLink: https://www.facebook.com//marketplace/item/1720260141839755/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 139}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 111K miles\nLocation: Fairfield, OH\nPrices: $9,850\nLink: https://www.facebook.com//marketplace/item/8207611969291247/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 140}\npage_content='Model: Nissan versa SL Sedan 4D\nYear: 2013\nMiles: 160K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1132833847775834/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 141}\npage_content='Model: Genesis g90 5.0 Ultimate Sedan 4D\nYear: 2021\nMiles: 22K miles\nLocation: Cincinnati, OH\nPrices: $51,118\nLink: https://www.facebook.com//marketplace/item/670265935284890/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 142}\npage_content='Model: Toyota prius One Hatchback 4D\nYear: 2015\nMiles: 111K miles\nLocation: Cincinnati, OH\nPrices: $9,999\nLink: https://www.facebook.com//marketplace/item/1371683937563859/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 143}\npage_content='Model: Lexus IS 350 Sport Sedan 4D\nYear: 2008\nMiles: 237K miles\nLocation: Cincinnati, OH\nPrices: $5,500\nLink: https://www.facebook.com//marketplace/item/726398496192253/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 144}\npage_content='Model: Chevrolet camaro LT Coupe 2D\nYear: 2012\nMiles: 108K miles\nLocation: Cincinnati, OH\nPrices: $7,200\nLink: https://www.facebook.com//marketplace/item/427355033049294/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 145}\npage_content='Model: Toyota matrix S Sport Wagon 4D\nYear: 2009\nMiles: 148K miles\nLocation: Burlington, KY\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/791749699752081/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 146}\npage_content='Model: Mitsubishi lancer GTS Sedan 4D\nYear: 2010\nMiles: 162K miles\nLocation: Fort Mitchell, KY\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/2215689042128543/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 147}\npage_content='Model: Chevrolet cruze LTZ Sedan 4D\nYear: 2015\nMiles: 113K miles\nLocation: Hebron, KY\nPrices: $123,456\nLink: https://www.facebook.com//marketplace/item/1401954563795275/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 148}\npage_content='Model: Honda crosstour EX-L Sport Utility 4D\nYear: 2012\nMiles: 153K miles\nLocation: Hamilton, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/987605822872560/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 149}\npage_content='Model: Chevrolet impala LT Sedan 4D\nYear: 2014\nMiles: 159K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/734720935354670/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 150}\npage_content='Model: Nissan altima 2.5 S Sedan 4D\nYear: 2007\nMiles: 173K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/833731498698015/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 151}\npage_content='Model: Mazda mazda6 s Sedan 4D\nYear: 2003\nMiles: 204K miles\nLocation: Cincinnati, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/3684694805134214/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 152}\npage_content='Model: Hyundai tiburon GS Coupe 2D\nYear: 2006\nMiles: 123K miles\nLocation: Fairfield, OH\nPrices: $2,600\nLink: https://www.facebook.com//marketplace/item/1013458523831682/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 153}\npage_content='Model: Infiniti q50 3.7 Sedan 4D\nYear: 2015\nMiles: 44K miles\nLocation: Erlanger, KY\nPrices: $18,500\nLink: https://www.facebook.com//marketplace/item/1122796235489721/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 154}\npage_content='Model: Tesla Model 3\nYear: 2018\nMiles: 33K miles\nLocation: Hamilton, OH\nPrices: $26,999\nLink: https://www.facebook.com//marketplace/item/967578921781014/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 155}\npage_content='Model: Toyota 4runner SR5 Sport Utility 4D\nYear: 2011\nMiles: 130K miles\nLocation: Cincinnati, OH\nPrices: $16,995\nLink: https://www.facebook.com//marketplace/item/1699766200789007/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 156}\npage_content='Model: Cadillac cts Sport Wagon 4D\nYear: 2012\nMiles: 153K miles\nLocation: Cincinnati, OH\nPrices: $5,900\nLink: https://www.facebook.com//marketplace/item/296036426928990/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 157}\npage_content='Model: Ford mustang GT Premium Convertible 2D\nYear: 2007\nMiles: 144K miles\nLocation: Batavia, OH\nPrices: $5,000\nLink: https://www.facebook.com//marketplace/item/837797351747161/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 158}\npage_content='Model: Chevrolet malibu LT Sedan 4D\nYear: 2013\nMiles: 169K miles\nLocation: Cincinnati, OH\nPrices: $4,000\nLink: https://www.facebook.com//marketplace/item/1418060278909190/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 159}\npage_content='Model: Ford fiesta SE Sedan 4D\nYear: 2014\nMiles: 70K miles\nLocation: Cleves, OH\nPrices: $3,500\nLink: https://www.facebook.com//marketplace/item/1926347357811390/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 160}\npage_content='Model: Audi a6 2.7T Quattro Sedan 4D\nYear: 2003\nMiles: 135K miles\nLocation: Batavia, OH\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/1563596657552324/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 161}\npage_content='Model: Acura tsx Sedan 4D\nYear: 2010\nMiles: 210K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/478238671460497/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 162}\npage_content='Model: Hyundai elantra Sport Sedan 4D\nYear: 2017\nMiles: 110K miles\nLocation: Cincinnati, OH\nPrices: $3,200\nLink: https://www.facebook.com//marketplace/item/772019378469877/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 163}\npage_content='Model: Lexus ES 350 Sedan 4D\nYear: 2008\nMiles: 161K miles\nLocation: Cincinnati, OH\nPrices: $4,200\nLink: https://www.facebook.com//marketplace/item/2549958651877636/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 164}\npage_content='Model: Acura tl\nYear: 2004\nMiles: 18K miles\nLocation: Cincinnati, OH\nPrices: $3,300\nLink: https://www.facebook.com//marketplace/item/1201602170981123/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 165}\npage_content='Model: Ford f150 supercrew cab Lariat Pickup 4D 5 1/2 ft\nYear: 2006\nMiles: 149K miles\nLocation: Cincinnati, OH\nPrices: $4,500\nLink: https://www.facebook.com//marketplace/item/388219000475181/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 166}\npage_content='Model: Mazda mazda3 s Sport Sedan 4D\nYear: 2008\nMiles: 301K miles\nLocation: Fort Thomas, KY\nPrices: $1,500\nLink: https://www.facebook.com//marketplace/item/1007653207468038/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 167}\npage_content='Model: Honda accord EX-L Sedan 4D\nYear: 2012\nMiles: 134K miles\nLocation: Fort Mitchell, KY\nPrices: $2,700\nLink: https://www.facebook.com//marketplace/item/490437083516646/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 168}\npage_content='Model: Toyota sienna XLE Minivan 4D\nYear: 2012\nMiles: 123K miles\nLocation: West Chester, OH\nPrices: $10,995\nLink: https://www.facebook.com//marketplace/item/1651976115603941/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 169}\npage_content='Model: Pontiac g6 gt\nYear: 2009\nMiles: 64K miles\nLocation: Cincinnati, OH\nPrices: $7,800\nLink: https://www.facebook.com//marketplace/item/7973219902745772/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 170}\npage_content='Model: Mazda mazda3\nYear: 2004\nMiles: 203K miles\nLocation: Florence, KY\nPrices: $1,749\nLink: https://www.facebook.com//marketplace/item/986810260115528/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 171}\npage_content='Model: Toyota camry SE Coupe 2D\nYear: 1996\nMiles: 200K miles\nLocation: Florence, KY\nPrices: $700\nLink: https://www.facebook.com//marketplace/item/781400517522902/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 172}\npage_content='Model: Honda civic Sport\nYear: 2024\nMiles: 10K miles\nLocation: Cincinnati, OH\nPrices: $1,234\nLink: https://www.facebook.com//marketplace/item/1111121573338243/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata={'row': 173}\npage_content='Model: Honda accord LX Sedan 4D\nYear: 2007\nMiles: 200K miles\nLocation: Cincinnati, OH\nPrices: $2,500\nLink: https://www.facebook.com//marketplace/item/813310967196628/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD\nScraped_On: 2024-07-10' metadata

In [94]:
message = ChatMessage(role="user", content=custom_prompt)
response = llm([message])
answer5 = response.content
print(response.content,end='\n')

Based on your criteria, the most suitable car for you would be:
- Model: Toyota Camry SE Nightshade Edition Sedan 4D
- Year: 2020
- Miles: 42K miles
- Location: Batavia, OH
- Price: $24,799
- Link: [Toyota Camry SE Nightshade Edition](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)

This car meets all your criteria as it is a Toyota, has low mileage, is a newer model, and is not from a dealership.

In [95]:
combined_answers = f"{answer1}\n--\n{answer2}\n--\n{answer3}\n--\n{answer4}\n--\n{answer5}"
print(combined_answers,end='\n')

Based on your preferences, the most suitable car for you would be the 2017 Honda Civic LX Sedan 4D with 72K miles, priced at $4,300. It is located in Loveland, OH and the link to the listing is https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD

This car meets your criteria of being a Honda, having less mileage, being affordable, and not being sold by a dealership. It is also a relatively newer model from 2017.
--
Based on your criteria, the most suitable car for you would be the 2017 Honda Accord LX Sedan 4D with 77K miles and a price of $6,200. It is located in Latonia, KY and is not from a dealership. You can view the listing here: [Honda Accord](https://www.facebook.com//marketplace/item/839430337752035/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)
--
Based on your criteria, the most suitable car for you would be the Toyota Camry SE Nightshade Edition Sedan 4D from 2020 with 42K miles and a price of $24,799. It is located in Batavia, OH and does not mention being sold by a dealership.

Link: [Toyota Camry SE Nightshade Edition](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)
--
Based on your criteria, the most suitable car for you would be the Toyota Camry SE Nightshade Edition Sedan 4D from 2020 with 42K miles priced at $24,799. It is a newer model with low mileage and fits your preferences for Toyota.

Here is the link to the listing: [Toyota Camry SE Nightshade Edition](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)

This car meets all your criteria as it is a Toyota, has low mileage, is a newer model, and is not from a dealership.
--
Based on your criteria, the most suitable car for you would be:
- Model: Toyota Camry SE Nightshade Edition Sedan 4D
- Year: 2020
- Miles: 42K miles
- Location: Batavia, OH
- Price: $24,799
- Link: [Toyota Camry SE Nightshade Edition](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD)

This car meets all your criteria as it is a Toyota, has low mileage, is a newer model, and is not from a dealership.

In [96]:
custom_prompt2 = f"""
Here is the data from the CSV file:\n{combined_answers}\n\n
1) Prettify this data using pointers and send me the response.
"""

In [97]:
message = ChatMessage(role="user", content=custom_prompt2)
response = llm([message])
formatted_answer = response.content
print(formatted_answer,end='\n')

1) Based on your preferences, the most suitable car for you would be the 2017 Honda Civic LX Sedan 4D with 72K miles, priced at $4,300. It is located in Loveland, OH and the link to the listing is [here](https://www.facebook.com//marketplace/item/873836418120474/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD).

2) Based on your criteria, the most suitable car for you would be the 2017 Honda Accord LX Sedan 4D with 77K miles and a price of $6,200. It is located in Latonia, KY and is not from a dealership. You can view the listing [here](https://www.facebook.com//marketplace/item/839430337752035/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD).

3) Based on your criteria, the most suitable car for you would be the Toyota Camry SE Nightshade Edition Sedan 4D from 2020 with 42K miles and a price of $24,799. It is located in Batavia, OH and does not mention being sold by a dealership. You can view the listing [here](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD).

4) Based on your criteria, the most suitable car for you would be the Toyota Camry SE Nightshade Edition Sedan 4D from 2020 with 42K miles priced at $24,799. It is a newer model with low mileage and fits your preferences for Toyota. You can view the listing [here](https://www.facebook.com//marketplace/item/3836295439951969/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3Ad707a518-1248-491d-a7cf-4548050d3f28&__tn__=!%3AD).